/* Stable Admin Dashboard + manual bank-transfer deposits and payouts. */
window.adminState={isAdmin:false,requests:[],deposits:[],rooms:[]};
async function checkAdmin(){if(!window.state?.user)return false;const q=await window.supabase.rpc('is_admin');window.adminState.isAdmin=!!q.data&&!q.error;return window.adminState.isAdmin}
async function loadAdmin(){if(window.__adminLoading)return;window.__adminLoading=true;try{if(!await checkAdmin()){alert('Admin access required.');return window.go('home')}const sb=window.supabase;const [q,d,r]=await Promise.all([sb.from('withdrawal_requests').select('id,user_id,amount,status,destination,created_at,processed_at').order('created_at',{ascending:false}).limit(200),sb.from('deposit_requests').select('id,user_id,amount,status,reference,created_at').order('created_at',{ascending:false}).limit(200),sb.rpc('admin_room_summary')]);if(q.error)throw q.error;if(d.error)throw d.error;window.adminState.requests=q.data||[];window.adminState.deposits=d.data||[];window.adminState.rooms=r.error?[]:(r.data||[]);const ids=[...new Set([...window.adminState.requests,...window.adminState.deposits].map(x=>x.user_id).filter(Boolean))];if(ids.length){const p=await sb.from('profiles').select('id,display_name,email').in('id',ids);if(!p.error){const pm=Object.fromEntries((p.data||[]).map(x=>[x.id,x]));window.adminState.requests=window.adminState.requests.map(x=>({...x,profiles:pm[x.user_id]||null}));window.adminState.deposits=window.adminState.deposits.map(x=>({...x,profiles:pm[x.user_id]||null}))}}window.state.page='admin';window.render()}catch(e){console.error('Admin load failed',e);alert('Admin data could not be loaded: '+(e.message||e))}finally{window.__adminLoading=false}}
async function approveWithdrawal(id){if(!confirm('Approve this withdrawal request?'))return;const q=await supabase.rpc('admin_approve_withdrawal',{p_request_id:id});if(q.error)return alert(q.error.message);loadAdmin()}
async function rejectWithdrawal(id){const reason=prompt('Reason for rejection (optional):')||'';const q=await supabase.rpc('admin_reject_withdrawal',{p_request_id:id,p_reason:reason});if(q.error)return alert(q.error.message);loadAdmin()}
async function markPaid(id){const reference=prompt('Enter transfer/reference number:');if(reference===null||!confirm('Confirm payment was sent externally?'))return;const q=await supabase.rpc('admin_mark_withdrawal_paid',{p_request_id:id,p_reference:reference});if(q.error)return alert(q.error.message);loadAdmin()}
async function approveDeposit(id){if(!confirm('Confirm this deposit was received and verified?'))return;const q=await supabase.rpc('approve_deposit_request',{p_request_id:id});if(q.error)return alert(q.error.message);loadAdmin()}
async function rejectDeposit(id){const reason=prompt('Reason for rejecting this deposit (optional):')||'';const q=await supabase.rpc('reject_deposit_request',{p_request_id:id,p_note:reason});if(q.error)return alert(q.error.message);loadAdmin()}
function parseDest(s){try{const x=JSON.parse(s||'{}');return x.bank?`${x.bank} • ${x.account_number} • ${x.account_name}`:s||'No account details'}catch{return s||'No account details'}}
function adminRequestRow(x){const who=x.profiles?.display_name||x.profiles?.email||x.user_id,date=new Date(x.created_at).toLocaleString();let a='';if(x.status==='pending')a=`<button class="secondary" onclick="approveWithdrawal('${x.id}')">Approve</button><button class="danger" onclick="rejectWithdrawal('${x.id}')">Reject</button>`;if(x.status==='approved')a=`<button class="primary" onclick="markPaid('${x.id}')">Mark PAID</button>`;return `<div class="admin-row"><div><b>${who}</b><div class="small">${date}</div></div><div><b>₦${Number(x.amount).toFixed(2)}</b><div class="small">${parseDest(x.destination)}</div></div><span class="status ${x.status}">${String(x.status).toUpperCase()}</span><div class="admin-actions">${a}</div></div>`}
function adminDepositRow(x){const who=x.profiles?.display_name||x.profiles?.email||x.user_id;let a='';if(x.status==='pending')a=`<button class="primary" onclick="approveDeposit('${x.id}')">APPROVE & CREDIT</button><button class="danger" onclick="rejectDeposit('${x.id}')">Reject</button>`;return `<div class="admin-row"><div><b>${who}</b><div class="small">${new Date(x.created_at).toLocaleString()}</div></div><div><b>₦${Number(x.amount).toFixed(2)}</b><div class="small">Ref: ${x.reference||'—'}</div></div><span class="status ${x.status}">${String(x.status).toUpperCase()}</span><div class="admin-actions">${a}</div></div>`}
function adminDashboard(){const p=window.adminState.deposits.filter(x=>x.status==='pending').length,w=window.adminState.requests.filter(x=>x.status==='pending').length;return `<div class="section"><div><span class="badge">ADMIN</span><h2>Control Dashboard</h2><p class="muted">Stable Admin control center.</p></div><div class="actions"><button class="secondary" onclick="go('home')">Exit Admin</button></div></div><div class="admin-stats"><div class="stat"><b>${p}</b><span>Deposits to verify</span></div><div class="stat"><b>${w}</b><span>Withdrawals pending</span></div><div class="stat"><b>${window.adminState.rooms.length}</b><span>Rooms</span></div></div><div class="panel"><h3>🔔 Deposit Requests</h3>${window.adminState.deposits.length?window.adminState.deposits.map(adminDepositRow).join(''):'<p class="muted">No deposit requests.</p>'}</div><div class="panel"><h3>Withdrawal Requests</h3>${window.adminState.requests.length?window.adminState.requests.map(adminRequestRow).join(''):'<p class="muted">No withdrawal requests.</p>'}</div><div class="panel"><h3>Room & Prize Overview</h3>${window.adminState.rooms.length?window.adminState.rooms.map(r=>`<div class="admin-row"><div><b>${r.room_name||'Room'}</b><div class="small">${r.room_code||''} • ${r.game_mode||''}</div></div><span class="status ${r.status||''}">${r.status||''}</span><div>Players: ${r.members||0}</div><div>Pool: ₦${Number(r.prize_pool||0).toFixed(2)}</div></div>`).join(''):'<p class="muted">No rooms found.</p>'}</div>`}
window.loadAdmin=loadAdmin;window.approveWithdrawal=approveWithdrawal;window.rejectWithdrawal=rejectWithdrawal;window.markPaid=markPaid;window.approveDeposit=approveDeposit;window.rejectDeposit=rejectDeposit;window.adminDashboard=adminDashboard;
