/* Admin Dashboard + manual bank-transfer deposits and payouts */
window.adminState={isAdmin:false,requests:[],deposits:[],rooms:[]};
async function checkAdmin(){if(!state.user)return false;const q=await supabase.rpc('is_admin');adminState.isAdmin=!!q.data&&!q.error;return adminState.isAdmin}
async function loadAdmin(){if(!await checkAdmin()){alert('Admin access required.');return go('home')}
 const q=await supabase.from('withdrawal_requests').select('id,user_id,amount,status,destination,created_at,processed_at,profiles(display_name,email)').order('created_at',{ascending:false}).limit(200);if(q.error)return alert(q.error.message);adminState.requests=q.data||[];
 const d=await supabase.from('deposit_requests').select('id,user_id,amount,method,reference,status,created_at,processed_at,profiles(display_name,email)').order('created_at',{ascending:false}).limit(200);if(d.error)return alert(d.error.message);adminState.deposits=d.data||[];
 const r=await supabase.rpc('admin_room_summary');if(r.error)return alert(r.error.message);adminState.rooms=r.data||[];state.page='admin';render()}
async function approveWithdrawal(id){if(!confirm('Approve this withdrawal request?'))return;const q=await supabase.rpc('admin_approve_withdrawal',{p_request_id:id});if(q.error)return alert(q.error.message);loadAdmin()}
async function rejectWithdrawal(id){const reason=prompt('Reason for rejection (optional):')||'';const q=await supabase.rpc('admin_reject_withdrawal',{p_request_id:id,p_reason:reason});if(q.error)return alert(q.error.message);loadAdmin()}
async function markPaid(id){const reference=prompt('Enter your manual transfer/reference number. Only do this AFTER you have sent the money externally:');if(reference===null)return;if(!confirm('Confirm the external bank payment has already been sent?'))return;const q=await supabase.rpc('admin_mark_withdrawal_paid',{p_request_id:id,p_reference:reference});if(q.error)return alert(q.error.message);loadAdmin()}
async function approveDeposit(id){if(!confirm('Confirm you received and verified this bank transfer?'))return;const q=await supabase.rpc('admin_approve_deposit',{p_request_id:id});if(q.error)return alert(q.error.message);loadAdmin()}
async function rejectDeposit(id){const reason=prompt('Reason for rejecting this deposit (optional):')||'';const q=await supabase.rpc('admin_reject_deposit',{p_request_id:id,p_reason:reason});if(q.error)return alert(q.error.message);loadAdmin()}
function parseDest(s){try{const x=JSON.parse(s||'{}');return x.bank?`${x.bank} • ${x.account_number} • ${x.account_name}`:s||'No account details';}catch{return s||'No account details'}}
function adminRequestRow(x){const who=x.profiles?.display_name||x.profiles?.email||x.user_id,date=new Date(x.created_at).toLocaleString();let actions='';if(x.status==='pending')actions=`<button class="secondary" onclick="approveWithdrawal('${x.id}')">Approve</button><button class="danger" onclick="rejectWithdrawal('${x.id}')">Reject</button>`;if(x.status==='approved')actions=`<button class="primary" onclick="markPaid('${x.id}')">Mark PAID</button><button class="danger" onclick="rejectWithdrawal('${x.id}')">Reject</button>`;return `<div class="admin-row"><div><b>${who}</b><div class="small">${date}</div></div><div><b>${Number(x.amount).toFixed(2)}</b><div class="small">${parseDest(x.destination)}</div></div><span class="status ${x.status}">${x.status.toUpperCase()}</span><div class="admin-actions">${actions}</div></div>`}
function adminDepositRow(x){const who=x.profiles?.display_name||x.profiles?.email||x.user_id,date=new Date(x.created_at).toLocaleString();let actions='';if(x.status==='pending')actions=`<button class="primary" onclick="approveDeposit('${x.id}')">Confirm RECEIVED</button><button class="danger" onclick="rejectDeposit('${x.id}')">Reject</button>`;return `<div class="admin-row"><div><b>${who}</b><div class="small">${date}</div></div><div><b>${Number(x.amount).toFixed(2)}</b><div class="small">Bank transfer • Ref: ${x.reference||'—'}</div></div><span class="status ${x.status}">${x.status.toUpperCase()}</span><div class="admin-actions">${actions}</div></div>`}
function adminDashboard(){const pending=adminState.requests.filter(x=>x.status==='pending'),approved=adminState.requests.filter(x=>x.status==='approved'),paid=adminState.requests.filter(x=>x.status==='paid'),depPending=adminState.deposits.filter(x=>x.status==='pending');return `<div class="section"><div><span class="badge">ADMIN</span><h2>Control Dashboard</h2><p class="muted">Manual bank-transfer management. You verify deposits and send withdrawals yourself.</p></div><div class="actions"><button class="secondary" onclick="adminSupport()">💬 Customer Care</button><button class="secondary" onclick="go('home')">Exit Admin</button></div></div><div class="admin-stats"><div class="stat"><b>${depPending.length}</b><span>Deposits to verify</span></div><div class="stat"><b>${pending.length}</b><span>Withdrawals pending</span></div><div class="stat"><b>${approved.length}</b><span>Ready to pay</span></div><div class="stat"><b>${paid.length}</b><span>Paid</span></div></div><div class="panel"><h3>Bank Transfer Deposits</h3>${adminState.deposits.length?adminState.deposits.map(adminDepositRow).join(''):'<p class="muted">No deposit requests.</p>'}</div><div class="panel"><h3>Withdrawal Requests</h3>${adminState.requests.length?adminState.requests.map(adminRequestRow).join(''):'<p class="muted">No withdrawal requests.</p>'}</div><div class="panel"><h3>Room & Prize Overview</h3>${adminState.rooms.length?adminState.rooms.map(r=>`<div class="admin-row"><div><b>${r.room_name}</b><div class="small">${r.room_code} • ${r.game_mode}</div></div><span class="status ${r.status}">${r.status}</span><div>Players: ${r.members}</div><div>Pool: ${Number(r.prize_pool||0).toFixed(2)}</div></div>`).join(''):'<p class="muted">No rooms found.</p>'}</div>`}
window.loadAdmin=loadAdmin;window.approveWithdrawal=approveWithdrawal;window.rejectWithdrawal=rejectWithdrawal;window.markPaid=markPaid;window.approveDeposit=approveDeposit;window.rejectDeposit=rejectDeposit;window.adminDashboard=adminDashboard;
