(function(){
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  async function presence(){if(window.state?.user&&window.supabase)try{await window.supabase.rpc('touch_presence')}catch(e){}}
  async function active(){if(!window.supabase)return[];const {data}=await window.supabase.rpc('get_active_users',{p_minutes:10});return data||[]}
  window.openSupportTicket=async function(){if(!window.state?.user)return window.go?.('auth');const c=prompt('Issue type: deposit_delay, withdrawal_delay, account, technical, or other','deposit_delay');if(!c)return;const s=prompt('Subject:','Payment/support request');if(!s)return;const m=prompt('Describe the issue and include amount/reference if relevant:');if(!m)return;const {error}=await window.supabase.rpc('open_support_ticket',{p_category:c,p_subject:s,p_message:m});alert(error?'Could not send support request: '+error.message:'Support request sent to the admin.');};
  async function avatar(file){if(!file||!window.state?.user)return;if(file.size>3*1024*1024)return alert('Profile picture must be 3MB or smaller.');if(!/^image\/(jpeg|png|webp)$/.test(file.type))return alert('Use JPG, PNG, or WebP.');const uid=window.state.user.id,ext=file.type.split('/')[1].replace('jpeg','jpg'),path=uid+'/avatar.'+ext;const {error}=await window.supabase.storage.from('avatars').upload(path,file,{upsert:true,contentType:file.type,cacheControl:'3600'});if(error)return alert('Upload failed: '+error.message);const {data}=window.supabase.storage.from('avatars').getPublicUrl(path);const q=await window.supabase.from('profiles').update({avatar_url:data.publicUrl+'?v='+Date.now()}).eq('id',uid);if(q.error)return alert(q.error.message);alert('Profile picture updated.');window.render?.();}
  async function enhance(){if(!window.state?.user)return;await presence();const wrap=document.querySelector('main.wrap');if(!wrap)return;if(!document.querySelector('#communityPanel')){const p=document.createElement('div');p.id='communityPanel';p.className='panel';p.style.marginTop='16px';p.innerHTML='<h3>Profile & Support</h3><p class="muted">Your Bet Name is public; legal and payout details stay private.</p><div class="actions"><label class="secondary" style="cursor:pointer">📷 Profile picture<input id="avatarFile" type="file" accept="image/jpeg,image/png,image/webp" style="display:none"></label><button class="secondary" onclick="openSupportTicket()">💬 Contact Admin</button></div><div id="activePlayers" style="margin-top:16px"></div>';wrap.appendChild(p);document.querySelector('#avatarFile').onchange=e=>avatar(e.target.files?.[0]);}
    const users=await active();const el=document.querySelector('#activePlayers');if(el)el.innerHTML='<h3>Players active now</h3>'+(users.length?'<div class="grid">'+users.map(u=>'<div class="card"><b>'+esc(u.bet_name||'Player')+'</b></div>').join('')+'</div>':'<p class="muted">No other players are active right now.</p>');}
  const oldRender=window.render;window.render=async function(){await oldRender();try{await enhance()}catch(e){console.warn('community:',e)}};
  setInterval(()=>presence(),60000);setInterval(()=>{try{window.supabase?.functions.invoke('sync-fixtures')}catch(e){}},15*60*1000);
})();
