import { rollDice, createDiceState, applyDiceRoll, currentDicePlayer, DICE_ROUNDS } from './src/games/diceEngine.js';

/* BetSquad Dice: exactly 4 rolls per player. Highest total after round 4 wins. */
(function(){'use strict';
const sb=()=>window.supabase, S=()=>window.state, players=()=>S()?.gameRoomPlayers||[];
const pid=()=>S()?.user?.id||null;
const name=id=>{const p=players().find(x=>(x.user_id||x.id)===id);return p?.display_name||(p?.is_bot?'Emeka':'Player')};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function room(){const id=S()?.gameRoomId;if(!id||!sb())return null;const q=await sb().from('game_rooms').select('*').eq('id',id).single();return q.error?null:q.data;}
function host(){return document.querySelector('#app .wrap')||document.querySelector('#app')||document.body;}
function rules(){return '<div class="notice"><b>🎲 How Dice works</b><ul><li>Each player rolls <b>two dice, 4 times</b>.</li><li>Every roll is added to that player’s total.</li><li>There is <b>no Hold rule</b> and rolling a 1 does <b>not</b> cancel your points.</li><li>After everyone completes Round 4, the player with the <b>highest total</b> wins.</li><li>If totals are equal, the game is a <b>tie</b>.</li></ul><p class="small muted">Example: 7 + 9 + 5 + 11 = <b>32 points</b> after four rolls.</p></div>';}
async function ensure(r){if(!r||r.game_type!=='dice'||r.status!=='active')return r;const s=r.state||{};if(s.dice?.playerIds?.length)return r;const ids=Array.isArray(s.order)?s.order:players().map(p=>p.user_id||p.id);if(ids.length<2)return r;const dice=createDiceState(ids,DICE_ROUNDS);const next={...s,dice,status:'active',order:ids};const q=await sb().from('game_rooms').update({state:next,status:'active'}).eq('id',r.id).eq('status','active').select('*').single();return q.error?{...r,state:next}:q.data;}
async function save(r,d){const next={...(r.state||{}),dice:d,order:d.playerIds,status:d.status};const status=d.status==='finished'?'finished':'active';const q=await sb().from('game_rooms').update({state:next,status}).eq('id',r.id).eq('status','active').select('*').single();return q.error?null:q.data;}
function paint(r){if(!r||r.game_type!=='dice')return;const d=r.state?.dice;if(!d){let p=document.getElementById('diceRulesHud');if(!p){p=document.createElement('section');p.id='diceRulesHud';p.className='panel';host().appendChild(p)}p.innerHTML='<span class="badge">🎲 DICE • ₦500</span><h2>Dice — 4 Rolls</h2>'+rules()+'<p><b>Players connected: '+players().length+'/2</b></p><p class="muted">The game starts automatically when 2 players are connected.</p>';return;}
let p=document.getElementById('diceRulesHud');if(!p){p=document.createElement('section');p.id='diceRulesHud';p.className='panel';host().appendChild(p)}
const me=pid(),turn=currentDicePlayer(d),mine=turn===me;
const rows=d.playerIds.map(id=>{const rs=d.rolls[id]||[];return '<div class="card" style="margin:8px 0"><div class="row"><b>'+esc(name(id))+'</b><b>'+Number(d.totals[id]||0)+' pts</b></div><div class="small muted">'+(rs.length?rs.map((r,i)=>'R'+(i+1)+': '+r.values.join(' + ')+' = '+r.total).join(' • '):'No rolls yet')+'</div></div>'}).join('');
let action='';if(d.status==='playing')action=mine?'<button type="button" class="primary" id="diceRollButton">🎲 ROLL DICE</button><p class="small muted">Your roll '+(d.rolls[me]?.length||0)+' of 4.</p>':'<p class="muted">Current turn: <b>'+esc(name(turn))+'</b></p>';
let finish='';if(d.status==='finished'){const ranked=[...d.playerIds].sort((a,b)=>(d.totals[b]||0)-(d.totals[a]||0));if(d.tie)finish='<div class="notice"><b>🤝 TIE GAME</b><br>Both players finished with '+Number(d.totals[ranked[0]]||0)+' points.</div>';else finish='<div class="notice"><b>🏆 '+esc(name(d.winner))+' WINS!</b><br>Final total: '+Number(d.totals[d.winner]||0)+' points after 4 rolls.</div>';}
const last=d.lastRoll?'<div class="notice" style="margin-top:10px">Last roll: <b>'+esc(name(d.lastRoll.playerId))+'</b> — 🎲 '+d.lastRoll.values.join(' + ')+' = '+d.lastRoll.total+' (Round '+d.lastRoll.round+')</div>':'';
p.innerHTML='<span class="badge">🎲 DICE • 4 ROLLS</span><h2>Dice Game</h2>'+rules()+'<p><b>Round '+Math.min(d.currentRound,DICE_ROUNDS)+' of '+DICE_ROUNDS+'</b></p>'+rows+last+'<div style="margin-top:14px">'+action+'</div>'+finish+'<button type="button" class="secondary" style="margin-top:12px" onclick="leaveGameRoom()">Leave Room</button>';
const b=document.getElementById('diceRollButton');if(b)b.onclick=window.rollMyDice;
}
window.rollMyDice=async function(){const r0=await room();if(!r0||r0.game_type!=='dice'||r0.status!=='active')return alert('Dice is still starting. Please wait a moment.');const r=await ensure(r0),d=r?.state?.dice,me=pid();if(!d||d.status!=='playing')return alert('This Dice game is finished.');if(currentDicePlayer(d)!==me)return alert('It is '+name(currentDicePlayer(d))+'\'s turn. Please wait.');if((d.rolls[me]||[]).length>=DICE_ROUNDS)return alert('You have completed all 4 rolls.');
try{applyDiceRoll(d,me,rollDice(2,6).values);}catch(e){return alert(e.message||'Could not roll dice.');}const saved=await save(r,d);if(!saved)return alert('Your roll could not be saved. Please try again.');S().gameRoomCache={room:saved,players:players()};paint(saved);if(d.status==='finished'){const winners=d.tie?[]:[d.winner];alert(d.tie?'🤝 The game is a tie!':'🏆 '+name(d.winner)+' wins with '+d.totals[d.winner]+' points!');await sb().rpc('game_settle_room',{p_room_id:saved.id,p_winner_ids:winners});}};
async function tick(){if(S()?.page!=='game_room'){document.getElementById('diceRulesHud')?.remove();return;}const r=await room();if(!r||r.game_type!=='dice'){document.getElementById('diceRulesHud')?.remove();return;}if(r.status==='waiting'){paint(r);return;}if(r.status==='active'){const ready=await ensure(r);S().gameRoomCache={room:ready,players:players()};paint(ready);return;}paint(r);}
setInterval(tick,1200);tick();
})();
