import { rollDice, createPigState, applyPigRoll, holdPigTurn } from './src/games/diceEngine.js';

(function(){
  const TARGET=100, BOT_DELAY=900;
  let botTimer=null;
  function playerId(){return window.state?.user?.id;}
  function isDiceRoom(room){return room?.game_type==='dice'&&room?.status==='active';}
  function botPid(){return (window.state?.gameRoomPlayers||[]).find(p=>p.is_bot)?.id||null;}
  async function getRoom(){const id=window.state?.gameRoomId,sb=window.supabase;if(!id||!sb)return null;const r=await sb.from('game_rooms').select('*').eq('id',id).single();return r.error?null:r.data;}
  async function ensurePig(room){if(!isDiceRoom(room))return room;const state=room.state||{};if(state.pig?.playerIds?.length)return room;const ids=Array.isArray(state.order)?state.order:((window.state.gameRoomPlayers||[]).map(p=>p.user_id||p.id));if(ids.length<2)return room;const pig=createPigState(ids,TARGET);const next={...state,rolls:{},pig,status:'active'};const saved=await window.supabase.from('game_rooms').update({state:next}).eq('id',room.id).eq('status','active').select('*').single();return saved.data||{...room,state:next};}
  async function savePig(room,pig){const next={...(room.state||{}),pig,rolls:{},order:pig.playerIds,status:pig.status};const r=await window.supabase.from('game_rooms').update({state:next,status:pig.status==='finished'?'finished':'active'}).eq('id',room.id).eq('status','active').select('*').single();return r.error?null:r.data;}
  function name(pid){const p=(window.state?.gameRoomPlayers||[]).find(x=>(x.user_id||x.id)===pid);return p?.display_name||(p?.is_bot?'Emeka':'Player');}
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function paint(room){if(!isDiceRoom(room)||!room.state?.pig)return;const p=room.state.pig,me=playerId(),panel=document.querySelector('#app .panel');if(!panel)return;const existing=panel.querySelector('#pigRulesHud');const html=`<div id="pigRulesHud" class="notice" style="margin-top:12px"><b>🎲 PIG — FIRST TO ${TARGET}</b><div class="small muted" style="margin-top:6px">Current turn: <b>${esc(name(p.currentPlayerId))}</b>${p.currentPlayerId===me?' — YOUR TURN':''}</div><div class="small" style="margin-top:6px">${p.playerIds.map(id=>`${esc(name(id))}: <b>${p.scores[id]||0}</b>`).join(' • ')}</div><div class="small muted" style="margin-top:6px">Turn points: <b>${p.turnScore||0}</b></div>${p.lastRoll?`<div class="small" style="margin-top:6px">Last roll: ${p.lastRoll.values.join(' + ')} = ${p.lastRoll.total}</div>`:''}${p.currentPlayerId===me&&p.status==='playing'?'<button type="button" class="secondary" id="pigHoldButton" style="margin-top:10px">✋ HOLD & BANK POINTS</button>':''}${p.status==='finished'?`<div style="margin-top:10px"><b>🏆 Winner: ${esc(name(p.winner))}</b><br><span class="small">Final score: ${p.scores[p.winner]||0}</span></div>`:''}</div>`;if(existing)existing.outerHTML=html;else panel.insertAdjacentHTML('beforeend',html);const hold=panel.querySelector('#pigHoldButton');if(hold&&!hold.dataset.bound){hold.dataset.bound='1';hold.onclick=window.holdPigDice;}}
  window.rollMyDice=async function(){const room=await getRoom();if(!isDiceRoom(room))return;const ready=await ensurePig(room),p=ready.state.pig,pid=playerId();if(p.status!=='playing'||p.currentPlayerId!==pid)return alert(p.currentPlayerId===pid?'Game is finished.':`It is ${name(p.currentPlayerId)}'s turn.`);const result=applyPigRoll(p,pid,rollDice(2,6).values),saved=await savePig(ready,p);if(!saved)return alert('Dice result could not be saved. Please try again.');window.state.gameRoomCache={room:saved,players:window.state.gameRoomPlayers||[]};if(result.event==='one_rolled')alert('You rolled a 1. Your turn points were lost.');if(result.event==='snake_eyes')alert('Snake eyes! Your total score has reset to 0.');paint(saved);maybeBot(saved.id);};
  window.holdPigDice=async function(){const room=await getRoom();if(!isDiceRoom(room))return;const ready=await ensurePig(room),p=ready.state.pig,pid=playerId();if(p.status!=='playing'||p.currentPlayerId!==pid)return;const result=holdPigTurn(p,pid),saved=await savePig(ready,p);if(!saved)return alert('Hold could not be saved. Please try again.');window.state.gameRoomCache={room:saved,players:window.state.gameRoomPlayers||[]};if(result.event==='winner'){alert(`🏆 ${name(pid)} wins with ${result.score} points!`);await settleWinner(saved.id,pid);}paint(saved);maybeBot(saved.id);};
  async function settleWinner(roomId,pid){const human=!(window.state.gameRoomPlayers||[]).find(p=>p.id===pid)?.is_bot;const r=await window.supabase.rpc('game_settle_room',{p_room_id:roomId,p_winner_ids:human?[pid]:[]});if(!r.error)window.state.gameSettlement=r.data;}
  function maybeBot(roomId){clearTimeout(botTimer);botTimer=setTimeout(async()=>{const room=await getRoom();if(!room||room.id!==roomId||!isDiceRoom(room))return;const bp=botPid(),pig=room.state?.pig;if(!bp||!pig||pig.status!=='playing'||pig.currentPlayerId!==bp)return;const result=applyPigRoll(pig,bp,rollDice(2,6).values);let saved=await savePig(room,pig);if(!saved)return;if(result.event==='safe_roll'&&pig.turnScore>=12&&pig.scores[bp]+pig.turnScore<TARGET){const held=holdPigTurn(pig,bp);saved=await savePig(saved,pig);if(held.event==='winner'){await settleWinner(saved.id,bp);return;}}paint(saved);if(saved.state?.pig?.status==='playing'&&saved.state.pig.currentPlayerId===bp)maybeBot(saved.id);},BOT_DELAY);}
  async function tick(){if(window.state?.page!=='game_room')return;const room=await getRoom();if(!isDiceRoom(room))return;const ready=await ensurePig(room);paint(ready);maybeBot(ready.id);}
  setInterval(tick,1000);
})();
