import { rollDice, createPigState, applyPigRoll, holdPigTurn } from './src/games/diceEngine.js';

/* Stable Dice/Pig runtime. Explains rules before play and gives clear roll feedback. */
(function(){'use strict';const TARGET=100;let botTimer=null;
function pid(){return window.state?.user?.id||null}function inRoom(){return window.state?.page==='game_room'}function dice(r){return r?.game_type==='dice'}function turn(p){return p?.playerIds?.[p.currentPlayerIndex]||null}function ps(){return window.state?.gameRoomPlayers||[]}function nm(id){const p=ps().find(x=>(x.user_id||x.id)===id);return p?.display_name||(p?.is_bot?'Emeka':'Player')}function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function room(){const id=window.state?.gameRoomId,sb=window.supabase;if(!id||!sb)return null;const q=await sb.from('game_rooms').select('*').eq('id',id).single();return q.error?null:q.data}
async function ensure(r){if(!dice(r)||r.status!=='active')return r;const s=r.state||{};if(s.pig?.playerIds?.length)return r;const ids=Array.isArray(s.order)?s.order:ps().map(p=>p.user_id||p.id);if(ids.length<2)return r;const pig=createPigState(ids,TARGET);const next={...s,pig,rolls:{},order:ids,status:'active'};const q=await window.supabase.from('game_rooms').update({state:next,status:'active'}).eq('id',r.id).eq('status','active').select('*').single();return q.error?{...r,state:next}:q.data}
async function save(r,p){const next={...(r.state||{}),pig:p,rolls:{},order:p.playerIds,status:p.status};const status=p.status==='finished'?'finished':'active';const q=await window.supabase.from('game_rooms').update({state:next,status}).eq('id',r.id).eq('status','active').select('*').single();return q.error?null:q.data}
function host(){return document.querySelector('#app .wrap')||document.querySelector('#app')||document.body}
function rules(){const box=document.createElement('div');box.className='notice';box.innerHTML='<b>🎲 How Dice (Pig) works</b><ul><li>First player to reach <b>100 points</b> wins.</li><li>On your turn, press <b>ROLL DICE</b>. Both dice are rolled.</li><li>If neither die is 1, the dice total is added to your <b>Turn Points</b>.</li><li>If <b>one die is 1</b>, your Turn Points become <b>0</b> and your turn ends. Your saved score is NOT lost.</li><li>If you roll <b>1 + 1 (Snake Eyes)</b>, your saved total score resets to <b>0</b> and your turn ends.</li><li>Press <b>HOLD & BANK</b> when you want to save your Turn Points permanently.</li></ul><p class="small muted">Example: score 30 + turn points 12 = 42 after Hold. Roll 1 before Hold = turn points 0, saved score remains 30.</p>';return box}
function waiting(r){let p=document.getElementById('pigRulesHud');if(!p){p=document.createElement('section');p.id='pigRulesHud';p.className='panel';host().appendChild(p)}p.innerHTML='<span class="badge">🎲 DICE • ₦500</span><h2>Classic Pig — 2 Dice</h2>'+rules().outerHTML+'<p><b>Players connected: '+ps().length+'/2</b></p><p class="muted">The game starts automatically when 2 players are connected.</p><button type="button" class="secondary" onclick="leaveGameRoom()">Leave Room & Refund</button>'}
function paint(r){if(!dice(r))return;const p=r.state?.pig;if(!p)return waiting(r);let panel=document.getElementById('pigRulesHud');if(!panel){panel=document.createElement('section');panel.id='pigRulesHud';panel.className='panel';host().appendChild(panel)}const me=pid(),who=turn(p),my=who===me,last=p.lastRoll?`<div class="notice" style="margin-top:10px">Last roll: <b>${p.lastRoll.values.join(' + ')} = ${p.lastRoll.total}</b></div>`:'';const scores=p.playerIds.map(id=>`<span style="display:inline-block;margin:4px 12px 4px 0"><b>${esc(nm(id))}</b>: ${p.scores[id]||0}</span>`).join('');let action='';if(p.status==='playing'&&my)action='<button type="button" class="primary" id="pigRollButton">🎲 ROLL DICE</button><button type="button" class="secondary" id="pigHoldButton" style="margin-left:8px">✋ HOLD & BANK</button>';else if(p.status==='playing')action='<p class="muted">Current turn: <b>'+esc(nm(who))+'</b></p>';const result=p.status==='finished'?`<div class="notice"><b>🏆 ${esc(nm(p.winner))} wins!</b> Final score: ${p.scores[p.winner]||0}</div>`:'';panel.innerHTML='<span class="badge">🎲 PIG • FIRST TO 100</span><h2>Dice Game</h2>'+rules().outerHTML+'<div style="margin:8px 0">'+scores+'</div><p>Turn Points: <b>'+Number(p.turnScore||0)+'</b></p>'+last+'<div style="margin-top:14px">'+action+'</div>'+result+'<button type="button" class="secondary" style="margin-top:12px" onclick="leaveGameRoom()">Leave Room</button>';const rb=document.getElementById('pigRollButton');if(rb)rb.onclick=window.rollMyDice;const hb=document.getElementById('pigHoldButton');if(hb)hb.onclick=window.holdPigDice}
window.rollMyDice=async function(){const r0=await room();if(!r0||!dice(r0)||r0.status!=='active')return alert('Dice is still starting. Please wait a moment.');const r=await ensure(r0),p=r?.state?.pig,me=pid();if(!p||p.status!=='playing')return alert('Dice is not active yet.');if(turn(p)!==me)return alert('It is '+nm(turn(p))+'\'s turn. Please wait.');let result;try{result=applyPigRoll(p,me,rollDice(2,6).values)}catch(e){return alert(e.message||'Could not roll dice.')}const saved=await save(r,p);if(!saved)return alert('The roll could not be saved. Please try again.');window.state.gameRoomCache={room:saved,players:ps()};paint(saved);if(result.event==='one_rolled')alert('You rolled a 1. Your Turn Points were lost, but your saved score is safe.');if(result.event==='snake_eyes')alert('Snake Eyes (1 + 1)! Your saved score has reset to 0.');maybeBot(saved.id)};
window.holdPigDice=async function(){const r0=await room();if(!r0||!dice(r0)||r0.status!=='active')return;const r=await ensure(r0),p=r?.state?.pig,me=pid();if(!p||p.status!=='playing'||turn(p)!==me)return;const result=holdPigTurn(p,me);const saved=await save(r,p);if(!saved)return alert('Hold could not be saved. Please try again.');window.state.gameRoomCache={room:saved,players:ps()};paint(saved);if(result.event==='winner'){alert('🏆 You win with '+result.score+' points!');await window.supabase.rpc('game_settle_room',{p_room_id:saved.id,p_winner_ids:[me]});return}maybeBot(saved.id)};
function botId(){return ps().find(p=>p.is_bot)?.id||null}function maybeBot(id){if(botTimer)return;botTimer=setTimeout(async()=>{botTimer=null;const r=await room();if(!r||r.id!==id||!dice(r)||r.status!=='active')return;const b=botId(),p=r.state?.pig;if(!b||!p||p.status!=='playing'||turn(p)!==b)return;const result=applyPigRoll(p,b,rollDice(2,6).values);let saved=await save(r,p);if(!saved)return;if(result.event==='safe_roll'&&(p.turnScore>=12||p.scores[b]+p.turnScore>=TARGET)){const held=holdPigTurn(p,b);saved=await save(saved,p);if(held.event==='winner'){await window.supabase.rpc('game_settle_room',{p_room_id:saved.id,p_winner_ids:[]});paint(saved);return}}paint(saved);if(saved.state?.pig?.status==='playing'&&turn(saved.state.pig)===b)maybeBot(saved.id)},900)}
async function tick(){if(!inRoom()){document.getElementById('pigRulesHud')?.remove();return}const r=await room();if(!r||!dice(r)){document.getElementById('pigRulesHud')?.remove();return}if(r.status==='waiting'){waiting(r);return}if(r.status==='active'){const ready=await ensure(r);window.state.gameRoomCache={room:ready,players:ps()};paint(ready);maybeBot(ready.id);return}paint(r)}
setInterval(tick,700);tick();})();
