/* Realistic game presentation layer for Whot, Dice and Snooker.
   It enhances the existing rule/game engine without replacing gameplay actions. */
(function(){
  'use strict';
  const suits={circle:'●',triangle:'▲',cross:'✚',square:'■',star:'★'};
  const colours={red:'#d22',yellow:'#e6c229',green:'#249447',brown:'#7b4a24',blue:'#287bd6',pink:'#e78bb5',black:'#111'};
  function css(){if(document.getElementById('realGameVisualCss'))return;const s=document.createElement('style');s.id='realGameVisualCss';s.textContent=`
  .real-board{margin:16px 0;padding:16px;border-radius:18px;background:linear-gradient(145deg,#0a1420,#111f30);border:1px solid #29415c;box-shadow:0 14px 40px #0006}
  .whot-table{display:flex;flex-wrap:wrap;gap:18px;align-items:center;justify-content:center;min-height:190px;background:radial-gradient(circle,#167044,#073c27);border-radius:16px;padding:22px;box-shadow:inset 0 0 0 8px #5b351b,inset 0 0 35px #0008}
  .whot-card{width:76px;height:108px;border-radius:9px;background:#fff;color:#111;border:2px solid #ddd;box-shadow:0 7px 12px #0007;display:flex;flex-direction:column;justify-content:space-between;padding:7px;font-weight:900;text-align:center;transform:rotate(var(--r));font-size:15px}.whot-card .big{font-size:30px}.whot-card.back{background:repeating-linear-gradient(45deg,#172b62 0 7px,#274c9a 7px 14px);color:#fff;border-color:#fff}.whot-hand{display:flex;gap:8px;overflow-x:auto;padding:12px 2px 5px;justify-content:center}.whot-hand .whot-card{flex:0 0 68px;height:96px;cursor:pointer}.whot-hand .whot-card:hover{transform:translateY(-10px) rotate(0)}
  .dice-table{display:flex;align-items:center;justify-content:center;gap:28px;min-height:190px;background:radial-gradient(circle,#174b32,#06281a);border-radius:16px;padding:30px;box-shadow:inset 0 0 0 8px #5b351b,inset 0 0 35px #0008}.die{width:82px;height:82px;background:linear-gradient(145deg,#fff,#d7d7d7);border-radius:14px;box-shadow:8px 10px 18px #0008,inset 2px 2px 4px #fff;display:grid;grid-template-columns:repeat(3,1fr);grid-template-rows:repeat(3,1fr);padding:10px}.pip{width:15px;height:15px;background:#111;border-radius:50%;align-self:center;justify-self:center}.d1 .pip:nth-child(1){grid-area:2/2}.d2 .pip:nth-child(1){grid-area:1/1}.d2 .pip:nth-child(2){grid-area:3/3}.d3 .pip:nth-child(1){grid-area:1/1}.d3 .pip:nth-child(2){grid-area:2/2}.d3 .pip:nth-child(3){grid-area:3/3}.d4 .pip:nth-child(1){grid-area:1/1}.d4 .pip:nth-child(2){grid-area:1/3}.d4 .pip:nth-child(3){grid-area:3/1}.d4 .pip:nth-child(4){grid-area:3/3}.d5 .pip:nth-child(1){grid-area:1/1}.d5 .pip:nth-child(2){grid-area:1/3}.d5 .pip:nth-child(3){grid-area:2/2}.d5 .pip:nth-child(4){grid-area:3/1}.d5 .pip:nth-child(5){grid-area:3/3}.d6 .pip:nth-child(1){grid-area:1/1}.d6 .pip:nth-child(2){grid-area:2/1}.d6 .pip:nth-child(3){grid-area:3/1}.d6 .pip:nth-child(4){grid-area:1/3}.d6 .pip:nth-child(5){grid-area:2/3}.d6 .pip:nth-child(6){grid-area:3/3}
  .snooker-wrap{background:#3b2113;padding:18px;border-radius:18px;box-shadow:0 14px 35px #0008}.snooker-table{position:relative;aspect-ratio:2/1;max-width:900px;margin:auto;background:radial-gradient(ellipse at center,#0b7540,#07552e 72%,#064326);border:12px solid #6b3e1f;border-radius:7%;box-shadow:inset 0 0 30px #0009,0 5px 12px #0008;overflow:hidden}.pocket{position:absolute;width:30px;height:30px;background:#050505;border-radius:50%;box-shadow:inset 0 3px 5px #555}.p1{left:-9px;top:-9px}.p2{right:-9px;top:-9px}.p3{left:-9px;bottom:-9px}.p4{right:-9px;bottom:-9px}.p5{left:50%;top:-9px;transform:translateX(-50%)}.p6{left:50%;bottom:-9px;transform:translateX(-50%)}.ball{position:absolute;width:22px;height:22px;border-radius:50%;box-shadow:inset 5px 4px 5px #fff9,inset -4px -4px 5px #0008,2px 3px 5px #0009;border:1px solid #fff5}.cue-ball{background:#eee}.red-ball{background:#c92828}.yellow-ball{background:#e6c229}.green-ball{background:#249447}.brown-ball{background:#7b4a24}.blue-ball{background:#287bd6}.pink-ball{background:#e78bb5}.black-ball{background:#111}.snooker-label{text-align:center;margin:8px 0 0;font-weight:800}.snooker-score{display:flex;justify-content:center;gap:24px;margin-bottom:10px;font-weight:800}
  @media(max-width:520px){.whot-card{width:62px;height:88px}.whot-card .big{font-size:25px}.die{width:68px;height:68px}.pip{width:12px;height:12px}.snooker-wrap{padding:10px}.snooker-table{border-width:8px}.ball{width:14px;height:14px}.pocket{width:21px;height:21px}}
  `;document.head.appendChild(s)}
  function card(c,extra){if(!c)return '';const sym=suits[c.suit]||c.suit;return `<div class="whot-card ${extra||''}" style="--r:${(Math.random()*4-2).toFixed(1)}deg"><span>${c.value===20?'WHOT':c.value}</span><span class="big">${c.value===20?'★':sym}</span><small>${c.suit}</small></div>`}
  function die(n){n=Math.max(1,Math.min(6,Number(n)||1));return `<div class="die d${n}">${Array.from({length:n},()=>'<i class="pip"></i>').join('')}</div>`}
  function snooker(){const pos=[['cue-ball',13,48],['red-ball',27,42],['red-ball',31,49],['red-ball',27,56],['red-ball',34,43],['red-ball',34,55],['red-ball',38,49],['red-ball',41,43],['red-ball',41,55],['red-ball',44,49],['yellow-ball',23,76],['green-ball',23,23],['brown-ball',50,49],['blue-ball',50,37],['pink-ball',63,49],['black-ball',78,49]];return `<div class="snooker-wrap"><div class="snooker-score"><span>🎱 SNOOKER</span></div><div class="snooker-table">${['p1','p2','p3','p4','p5','p6'].map(x=>`<i class="pocket ${x}"></i>`).join('')}${pos.map(([cl,x,y])=>`<i class="ball ${cl}" style="left:${x}%;top:${y}%;transform:translate(-50%,-50%)"></i>`).join('')}</div><div class="snooker-label">Real table • 15 reds + colours • balls are shown on the table</div></div>`}
  function mount(){
    if(!window.state||window.state.page!=='game_room')return;
    const room=window.state.gameRoomCache?.room;if(!room||room.status!=='active')return;
    const panel=document.querySelector('#app .wrap .panel');if(!panel)return;
    if(panel.querySelector('.real-board'))return;
    const board=document.createElement('div');board.className='real-board';
    if(room.game_type==='whot'){
      const st=room.state||{},pid=window.state.user?.id,hand=st.hands?.[pid]||[];
      board.innerHTML=`<div style="text-align:center;font-weight:900;margin-bottom:10px">🃏 WHOT TABLE</div><div class="whot-table"><div class="whot-card back"><span>WHOT</span><span class="big">★</span><small>DRAW</small></div>${card(st.topCard)}</div><div class="whot-hand">${hand.map(c=>card(c)).join('')}</div>`;
    } else if(room.game_type==='dice'){
      const vals=room.state?.rolls?.[window.state.user?.id]?.values||[];board.innerHTML=`<div style="text-align:center;font-weight:900;margin-bottom:10px">🎲 LIVE DICE TABLE</div><div class="dice-table">${(vals.length?vals:[1,1]).map(die).join('')}</div><div style="text-align:center;margin-top:10px">${vals.length?'Your rolled dice':'Roll to reveal your real dice'}</div>`;
    } else if(room.game_type==='snooker') board.innerHTML=snooker();
    else return;
    panel.insertBefore(board,panel.firstChild);
  }
  css();
  const mo=new MutationObserver(mount);mo.observe(document.documentElement,{childList:true,subtree:true});setInterval(mount,700);mount();
})();
