(() => {
  'use strict';
  const state={peers:new Map(),pendingIce:new Map(),stream:null,muted:false,roomId:null,channel:null,joined:false,userId:null,soundEnabled:false,open:true,dragging:false,x:null,y:null};
  const cfg={iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'}]};
  const roomId=()=>window.state?.gameRoomId||window.state?.friendlyMatchId||window.state?.roomId||null;
  const userId=()=>window.state?.user?.id||null;
  const send=(to,type,payload={})=>{if(!state.channel||!state.joined)return;state.channel.send({type:'broadcast',event:'voice-signal',payload:{from:state.userId,to,type,...payload}})};
  async function playRemoteAudio(el){if(!el||!state.soundEnabled)return false;try{await el.play();return true}catch(e){el.dataset.playBlocked='1';return false}}
  function enableRemoteSound(){state.soundEnabled=true;document.querySelectorAll('[id^="voice-audio-"]').forEach(el=>{el.muted=false;el.volume=1;playRemoteAudio(el)});renderVoice('🔊 Sound enabled — you can hear other players.');}
  function ensureAudio(id,stream){let el=document.querySelector('#voice-audio-'+id);if(!el){el=document.createElement('audio');el.id='voice-audio-'+id;el.autoplay=true;el.playsInline=true;el.setAttribute('aria-label','Opponent voice');el.style.display='none';document.body.appendChild(el)}el.srcObject=stream;el.muted=false;el.volume=1;if(state.soundEnabled)playRemoteAudio(el);else renderVoice('🎧 Opponent connected — tap Enable sound to hear them.');}
  async function makePeer(id,initiator){if(!state.stream||!id||id===state.userId)return null;let pc=state.peers.get(id);if(pc)return pc;pc=new RTCPeerConnection(cfg);state.peers.set(id,pc);state.stream.getTracks().forEach(t=>pc.addTrack(t,state.stream));pc.onicecandidate=e=>{if(e.candidate)send(id,'ice',{candidate:e.candidate})};pc.ontrack=e=>{if(e.streams[0])ensureAudio(id,e.streams[0])};pc.onconnectionstatechange=()=>{if(pc.connectionState==='connected')renderVoice('🟢 Voice connected — talking live.');if(['failed','closed'].includes(pc.connectionState)){pc.close();state.peers.delete(id);document.querySelector('#voice-audio-'+id)?.remove();renderVoice('⚠️ Voice connection ended.')}if(pc.connectionState==='disconnected')renderVoice('⚠️ Voice connection interrupted.')};if(initiator){const offer=await pc.createOffer({offerToReceiveAudio:true});await pc.setLocalDescription(offer);send(id,'offer',{description:pc.localDescription})}return pc}
  async function handleSignal(p){if(!p||p.from===state.userId||!state.stream)return;if(p.type==='hello'){await makePeer(p.from,state.userId<p.from);return}if(p.to!==state.userId)return;if(p.type==='offer'){const pc=await makePeer(p.from,false);if(!pc)return;await pc.setRemoteDescription(new RTCSessionDescription(p.description));for(const c of state.pendingIce.get(p.from)||[]){try{await pc.addIceCandidate(c)}catch(_){}}state.pendingIce.delete(p.from);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);send(p.from,'answer',{description:pc.localDescription})}else if(p.type==='answer'){const pc=state.peers.get(p.from);if(pc){await pc.setRemoteDescription(new RTCSessionDescription(p.description));for(const c of state.pendingIce.get(p.from)||[]){try{await pc.addIceCandidate(c)}catch(_){}}state.pendingIce.delete(p.from)}}else if(p.type==='ice'){const pc=state.peers.get(p.from);if(pc?.remoteDescription){try{await pc.addIceCandidate(p.candidate)}catch(_){}}else{const q=state.pendingIce.get(p.from)||[];q.push(p.candidate);state.pendingIce.set(p.from,q)}}}
  function connectChannel(){const rid=roomId(),uid=userId();if(!rid||!uid||!window.supabase)return false;if(state.channel&&state.roomId===rid&&state.userId===uid)return true;if(state.channel)window.supabase.removeChannel(state.channel);state.roomId=rid;state.userId=uid;state.joined=false;state.channel=window.supabase.channel('voice-room-'+rid,{config:{broadcast:{self:false}}});state.channel.on('broadcast',{event:'voice-signal'},({payload})=>handleSignal(payload));state.channel.subscribe(status=>{if(status==='SUBSCRIBED'){state.joined=true;send(null,'hello');renderVoice('Connected — waiting for other players…')}});return true}
  async function join(){if(!roomId())return alert('Join a game room before using voice chat.');if(!userId())return alert('Please sign in before joining voice chat.');if(!navigator.mediaDevices?.getUserMedia||!window.RTCPeerConnection)return alert('Voice chat is not supported by this browser.');try{if(!state.stream)state.stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});state.soundEnabled=true;if(!connectChannel())throw new Error('Could not connect to the game voice channel.');renderVoice('🎙️ Microphone on — connecting to other players…')}catch(e){alert('Could not start voice chat: '+(e.message||e))}}
  const toggleMute=()=>{state.muted=!state.muted;state.stream?.getAudioTracks().forEach(t=>t.enabled=!state.muted);renderVoice(state.muted?'🔇 Microphone muted':'🎙️ Microphone on')};
  function cleanup(){state.peers.forEach(pc=>pc.close());state.peers.clear();state.pendingIce.clear();if(state.channel&&window.supabase)window.supabase.removeChannel(state.channel);state.channel=null;state.joined=false;state.stream?.getTracks().forEach(t=>t.stop());state.stream=null;state.roomId=null;state.userId=null;state.soundEnabled=false;document.querySelectorAll('[id^="voice-audio-"]').forEach(e=>e.remove())}
  function savePosition(){try{localStorage.setItem('betsquad.voice.position',JSON.stringify({x:state.x,y:state.y,open:state.open}))}catch(_) {}}
  function loadPosition(){try{const p=JSON.parse(localStorage.getItem('betsquad.voice.position')||'null');if(p){state.x=Number.isFinite(p.x)?p.x:null;state.y=Number.isFinite(p.y)?p.y:null;state.open=p.open!==false}}catch(_) {}}
  function applyPosition(box){if(state.x!=null&&state.y!=null){const maxX=Math.max(0,innerWidth-box.offsetWidth);const maxY=Math.max(0,innerHeight-box.offsetHeight);state.x=Math.min(Math.max(0,state.x),maxX);state.y=Math.min(Math.max(0,state.y),maxY);box.style.left=state.x+'px';box.style.top=state.y+'px';box.style.right='auto';box.style.bottom='auto'}}
  function makeDraggable(box,handle){let sx=0,sy=0,ox=0,oy=0;const move=(e)=>{if(!state.dragging)return;const p=e.touches?.[0]||e;state.x=ox+(p.clientX-sx);state.y=oy+(p.clientY-sy);applyPosition(box)};const end=()=>{if(state.dragging){state.dragging=false;box.classList.remove('dragging');savePosition()}};const start=(e)=>{if(e.target.closest('button'))return;const r=box.getBoundingClientRect(),p=e.touches?.[0]||e;state.dragging=true;box.classList.add('dragging');sx=p.clientX;sy=p.clientY;ox=r.left;oy=r.top;e.preventDefault()};handle.addEventListener('pointerdown',start);window.addEventListener('pointermove',move);window.addEventListener('pointerup',end);handle.addEventListener('touchstart',start,{passive:false});window.addEventListener('touchmove',move,{passive:false});window.addEventListener('touchend',end)}
  function toggleOpen(){state.open=!state.open;savePosition();renderVoice(state.open?'Voice panel opened':'Voice panel closed')}
  function renderVoice(statusText){let box=document.querySelector('#voiceChatBox');if(!box){box=document.createElement('div');box.id='voiceChatBox';document.body.appendChild(box);loadPosition();}
    box.className='voice-chat-floating'+(state.open?'':' voice-collapsed');
    box.style.cssText='position:fixed;z-index:99999;right:18px;bottom:18px;width:min(360px,calc(100vw - 36px));padding:0;border:1px solid #2b4058;border-radius:14px;background:#0b1b2d;color:#edf5ff;box-shadow:0 12px 35px rgba(0,0,0,.35);font-family:system-ui,sans-serif;overflow:hidden;touch-action:none;'+(state.x!=null&&state.y!=null?'left:'+state.x+'px;top:'+state.y+'px;right:auto;bottom:auto;':'');
    box.innerHTML=`<div class="voice-chat-title" style="display:flex;align-items:center;justify-content:space-between;font-weight:700;padding:12px;cursor:move;user-select:none"><span>🎙️ Voice chat <span style="font-size:11px;opacity:.7">drag</span></span><button id="voiceClose" style="border:0;border-radius:8px;padding:5px 9px;cursor:pointer">${state.open?'−':'+'}</button></div>${state.open?`<div style="padding:0 12px 12px"><div class="voice-chat-actions" style="display:flex;gap:8px;flex-wrap:wrap"><button id="voiceJoin" class="voice-main">${state.stream?'Voice on':'Join voice'}</button><button id="voiceSound" ${state.stream?'':'disabled'}>🔊 ${state.soundEnabled?'Sound on':'Enable sound'}</button><button id="voiceMute" ${state.stream?'':'disabled'}>${state.muted?'Unmute':'Mute'}</button></div><div id="voiceStatus" style="margin-top:9px;font-size:13px;color:#aebfd3;min-height:18px">${statusText||(state.stream?'Microphone connected':'Join voice to talk with your opponent')}</div></div>`:''}`;
    box.querySelector('#voiceClose').onclick=toggleOpen;
    if(state.open){box.querySelector('#voiceJoin').onclick=join;box.querySelector('#voiceSound').onclick=enableRemoteSound;box.querySelector('#voiceMute').onclick=toggleMute;}
    if(!box.dataset.dragReady){makeDraggable(box,box.querySelector('.voice-chat-title'));box.dataset.dragReady='1'}
    applyPosition(box);
  }
  window.gameVoiceChat={join,cleanup,toggleMute,enableRemoteSound,toggleOpen};
  setInterval(()=>{const rid=roomId();if(rid&&userId()&&state.stream&&(!state.channel||state.roomId!==rid))connectChannel()},1500);
  window.addEventListener('beforeunload',cleanup);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',renderVoice);else renderVoice();
})();