(() => {
  'use strict';
  const state = { peers:new Map(), pendingIce:new Map(), stream:null, muted:false, roomId:null, channel:null, joined:false, userId:null };
  const cfg={iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'}]};
  const roomId=()=>window.state?.gameRoomId||window.state?.friendlyMatchId||window.state?.roomId||null;
  const userId=()=>window.state?.user?.id||null;
  const send=(to,type,payload={})=>{if(!state.channel||!state.joined)return;state.channel.send({type:'broadcast',event:'voice-signal',payload:{from:state.userId,to,type,...payload}})};
  const ensureAudio=(id,stream)=>{let el=document.querySelector('#voice-audio-'+id);if(!el){el=document.createElement('audio');el.id='voice-audio-'+id;el.autoplay=true;el.playsInline=true;el.style.display='none';document.body.appendChild(el)}el.srcObject=stream;el.play().catch(()=>{})};
  async function makePeer(id,initiator){if(!state.stream||!id||id===state.userId)return null;let pc=state.peers.get(id);if(pc)return pc;pc=new RTCPeerConnection(cfg);state.peers.set(id,pc);state.stream.getTracks().forEach(t=>pc.addTrack(t,state.stream));pc.onicecandidate=e=>{if(e.candidate)send(id,'ice',{candidate:e.candidate})};pc.ontrack=e=>{if(e.streams[0])ensureAudio(id,e.streams[0])};pc.onconnectionstatechange=()=>{if(['failed','closed','disconnected'].includes(pc.connectionState)){if(pc.connectionState==='failed'){pc.close();state.peers.delete(id)}document.querySelector('#voice-audio-'+id)?.remove()}};if(initiator){const offer=await pc.createOffer({offerToReceiveAudio:true});await pc.setLocalDescription(offer);send(id,'offer',{description:pc.localDescription})}return pc}
  async function handleSignal(p){if(!p||p.from===state.userId||!state.stream)return;if(p.type==='hello'){await makePeer(p.from,state.userId<p.from);return}if(p.to!==state.userId)return;if(p.type==='offer'){const pc=await makePeer(p.from,false);if(!pc)return;await pc.setRemoteDescription(new RTCSessionDescription(p.description));const queued=state.pendingIce.get(p.from)||[];for(const c of queued){try{await pc.addIceCandidate(c)}catch(_){}}state.pendingIce.delete(p.from);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);send(p.from,'answer',{description:pc.localDescription})}else if(p.type==='answer'){const pc=state.peers.get(p.from);if(pc){await pc.setRemoteDescription(new RTCSessionDescription(p.description));const queued=state.pendingIce.get(p.from)||[];for(const c of queued){try{await pc.addIceCandidate(c)}catch(_){}}state.pendingIce.delete(p.from)}}else if(p.type==='ice'){const pc=state.peers.get(p.from);if(pc?.remoteDescription){try{await pc.addIceCandidate(p.candidate)}catch(_){}}else{const q=state.pendingIce.get(p.from)||[];q.push(p.candidate);state.pendingIce.set(p.from,q)}}}
  function connectChannel(){const rid=roomId(),uid=userId();if(!rid||!uid||!window.supabase)return false;if(state.channel&&state.roomId===rid&&state.userId===uid)return true;if(state.channel)window.supabase.removeChannel(state.channel);state.roomId=rid;state.userId=uid;state.joined=false;state.channel=window.supabase.channel('voice-room-'+rid,{config:{broadcast:{self:false}}});state.channel.on('broadcast',{event:'voice-signal'},({payload})=>handleSignal(payload)).subscribe(status=>{if(status==='SUBSCRIBED'){state.joined=true;send(null,'hello')}});return true}
  async function join(){if(!roomId())return alert('Join a game room before using voice chat.');if(!userId())return alert('Please sign in before joining voice chat.');if(!navigator.mediaDevices?.getUserMedia||!window.RTCPeerConnection)return alert('Voice chat is not supported by this browser.');try{if(!state.stream)state.stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});if(!connectChannel())throw new Error('Could not connect to the game voice channel.');renderVoice('Connected — waiting for other players')}catch(e){alert('Could not start voice chat: '+(e.message||e))}}
  const toggleMute=()=>{state.muted=!state.muted;state.stream?.getAudioTracks().forEach(t=>t.enabled=!state.muted);renderVoice()};
  function cleanup(){state.peers.forEach(pc=>pc.close());state.peers.clear();state.pendingIce.clear();if(state.channel&&window.supabase)window.supabase.removeChannel(state.channel);state.channel=null;state.joined=false;state.stream?.getTracks().forEach(t=>t.stop());state.stream=null;state.roomId=null;state.userId=null;document.querySelectorAll('[id^="voice-audio-"]').forEach(e=>e.remove())}
  function renderVoice(statusText){let box=document.querySelector('#voiceChatBox');if(!box){box=document.createElement('div');box.id='voiceChatBox';document.body.appendChild(box)}box.className='voice-chat-floating';box.innerHTML=`<div class="voice-chat-title"><span>🎙️ Voice</span><span class="voice-dot ${state.stream?'on':''}"></span></div><div class="voice-chat-actions"><button id="voiceJoin" class="voice-main">${state.stream?'Connected':'Join voice'}</button><button id="voiceMute" ${state.stream?'':'disabled'}>${state.muted?'Unmute':'Mute'}</button></div><div id="voiceStatus" class="voice-chat-status">${statusText||(state.stream?'Microphone connected':'Tap Join voice to talk')}</div>`;box.querySelector('#voiceJoin').onclick=join;box.querySelector('#voiceMute').onclick=toggleMute}
  const style=document.createElement('style');style.textContent=`#voiceChatBox.voice-chat-floating{position:fixed;right:16px;bottom:16px;z-index:99999;width:min(280px,calc(100vw - 24px));box-sizing:border-box;background:rgba(17,17,17,.96);color:#fff;padding:12px;border-radius:16px;box-shadow:0 8px 30px rgba(0,0,0,.3);font:14px system-ui,sans-serif;backdrop-filter:blur(8px)}.voice-chat-title{display:flex;align-items:center;justify-content:space-between;font-weight:700;margin-bottom:9px}.voice-dot{width:9px;height:9px;border-radius:50%;background:#777}.voice-dot.on{background:#2ecc71;box-shadow:0 0 8px #2ecc71}.voice-chat-actions{display:flex;gap:7px}.voice-chat-actions button{flex:1;min-height:42px;border:0;border-radius:10px;padding:8px 10px;font-weight:700;cursor:pointer}.voice-chat-actions .voice-main{background:#20a464;color:#fff}.voice-chat-actions button:not(.voice-main){background:#eee;color:#111}.voice-chat-actions button:disabled{opacity:.45;cursor:not-allowed}.voice-chat-status{font-size:12px;opacity:.75;margin-top:8px;line-height:1.35}@media(max-width:600px){#voiceChatBox.voice-chat-floating{right:10px;bottom:max(10px,env(safe-area-inset-bottom));width:calc(100vw - 20px);padding:11px;border-radius:14px}.voice-chat-actions button{min-height:46px;font-size:14px}}@media(min-width:601px){#voiceChatBox.voice-chat-floating{bottom:20px;right:20px}}`;document.head.appendChild(style);
  setInterval(()=>{const rid=roomId();if(rid&&userId()&&state.stream&&(!state.channel||state.roomId!==rid))connectChannel()},1500);
  window.addEventListener('beforeunload',cleanup);window.gameVoiceChat={join,cleanup,toggleMute};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',renderVoice);else renderVoice();
})();