/* BetSquad games hub and room coordinator. Dice is intentionally delegated to dice_pig_runtime.js. */
import { createDeck, canPlay, validateWhotAction, nextPlayer, SUITS, DEFAULT_HAND_SIZE } from './src/games/whotEngine.js';
import { createDiceState } from './src/games/diceEngine.js';
import { createSnookerState, scorePot, applyFoul, finishSnooker, BALL_VALUES } from './src/games/snookerEngine.js';
import { secureInt } from './src/games/fairRandom.js';
import { GAME_RULES, BOT_RULES } from './game_engine_config.js';

const RULES={whot:GAME_RULES.WHOT,dice:GAME_RULES.DICE,snooker:GAME_RULES.SNOOKER};
const BOT_WAIT_MS=15000;
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function shuffle(a){const x=[...a];for(let i=x.length-1;i>0;i--){const j=secureInt(0,i);[x[i],x[j]]=[x[j],x[i]];}return x;}
function cardLabel(c){if(!c)return'?';const icons={circle:'●',triangle:'▲',cross:'✚',square:'■',star:'★'};return c.value===20?'WHOT ★':`${icons[c.suit]||c.suit} ${c.value}`;}
function isBotPid(pid){return !(window.state.gameRoomPlayers||[]).some(p=>!p.is_bot&&p.user_id===pid);}
function playerName(players,pid){const p=(players||[]).find(x=>(x.user_id||x.id)===pid);return p?.display_name||(p?.is_bot?BOT_RULES.name:'Player');}
function renderGamesHub(){const app=document.querySelector('#app');if(!app)return;const cards=[['whot','🃏','Whot','Fast-paced card battles, up to 4 players'],['dice','🎲','Dice','One six-sided die, 4 rolls each, highest total wins'],['snooker','🎱','Snooker','1v1 skill-based scoring']];app.innerHTML=`<div class="wrap"><div class="section"><h2>Games</h2></div><p class="muted" style="margin-top:-8px">Play Whot, Dice or Snooker. Entry is ₦500.</p><div class="grid">${cards.map(([id,icon,name,desc])=>`<div class="card"><span class="badge">${icon} ₦500 ENTRY</span><h3>${name}</h3><p class="muted">${desc}</p><button class="primary" style="width:100%;margin-top:10px" onclick="playGame('${id}')">Find a room</button></div>`).join('')}</div></div>`;}
window.playGame=async function(type){const s=window.state;if(s.gameStarting)return;if(!s.user)return window.go?.('auth');const rules=RULES[type];if(!rules)return alert('This game is not available.');const sb=window.supabase;s.gameStarting=true;try{let room=null;const {data:openRooms,error:re}=await sb.from('game_rooms').select('id,capacity,status,stake').eq('game_type',type).eq('status','waiting').order('created_at',{ascending:true}).limit(10);if(re)throw re;for(const r of openRooms||[]){const {count,error}=await sb.from('game_room_players').select('id',{count:'exact',head:true}).eq('room_id',r.id);if(error)throw error;if((count||0)<r.capacity){room=r;break;}}if(!room){const {data:created,error}=await sb.from('game_rooms').insert({game_code:type,game_type:type,room_type:'public',entry_fee:rules.entryFee,stake:rules.entryFee,max_players:rules.capacity,capacity:rules.capacity,created_by:s.user.id,creator_id:s.user.id,bot_allowed:type!=='dice',state:{}}).select().single();if(error)throw error;room=created;}const {data:check,error:ce}=await sb.from('game_rooms').select('status,capacity,stake,game_type').eq('id',room.id).single();if(ce)throw ce;if(!check||check.status!=='waiting'){alert('That room just filled up — try again.');return;}const displayName=s.user.user_metadata?.name||(s.user.email||'Player').split('@')[0];const {error:je}=await sb.from('game_room_players').insert({room_id:room.id,user_id:s.user.id,display_name:displayName,stake_amount:Number(check.stake||rules.entryFee),is_bot:false});if(je){if(je.code==='23505')alert('You are already in this room.');else throw je;return;}const debit=await sb.rpc('game_debit_stake',{p_amount:rules.entryFee});if(debit.error||!debit.data){await sb.from('game_room_players').delete().eq('room_id',room.id).eq('user_id',s.user.id);alert('Insufficient cash balance. Deposit at least ₦'+rules.entryFee+'.');return;}s.gameType=type;s.gameRoomId=room.id;s.gameWaitStarted=Date.now();s.gameRoomCache=null;s.gameSettlement=null;s.__diceRendered=false;s.page='game_room';window.render();startGamePolling();}catch(e){console.error('Game start failed',e);alert('Could not start the game: '+(e?.message||e));}finally{s.gameStarting=false;}};
window.leaveGameRoom=async function(){const s=window.state,sb=window.supabase;if(s.gameRoomId&&s.gameRoomCache?.room?.status==='waiting'){try{await sb.rpc('game_refund_stake',{p_room_id:s.gameRoomId});}catch(e){console.warn('refund failed',e);}}stopGamePolling();s.gameRoomId=null;s.gameRoomCache=null;s.gameSettlement=null;s.gameRoomPlayers=[];s.__diceRendered=false;s.page='games';window.render();};
let pollTimer=null,initializing=false,lastWaitingKey='';
function startGamePolling(){stopGamePolling();pollTimer=setInterval(tick,2000);tick();}
function stopGamePolling(){if(pollTimer){clearInterval(pollTimer);pollTimer=null;}}
async function tick(){const s=window.state;if(s.page!=='game_room'||!s.gameRoomId){stopGamePolling();return;}const sb=window.supabase;const [{data:room,error:re},{data:players,error:pe}]=await Promise.all([sb.from('game_rooms').select('*').eq('id',s.gameRoomId).single(),sb.from('game_room_players').select('*').eq('room_id',s.gameRoomId).order('joined_at',{ascending:true})]);if(re||pe||!room){stopGamePolling();return;}s.gameRoomCache={room,players:players||[]};s.gameRoomPlayers=players||[];if(room.status==='waiting'){const humans=(players||[]).filter(p=>!p.is_bot);const leader=humans[0];if(leader?.user_id===s.user.id&&!initializing){const ready=room.game_type==='dice'?humans.length>=2:readyCheck(room.game_type,players||[],s.gameWaitStarted||Date.now());if(ready){initializing=true;try{if(room.game_type==='whot')await initWhot(room,players||[]);else if(room.game_type==='dice')await initDice(room,players||[]);else if(room.game_type==='snooker')await initSnooker(room,players||[]);}catch(e){console.error('Game init failed',e);}finally{initializing=false;}}}if(room.game_type!=='dice'||lastWaitingKey!==room.id+':'+players.length){lastWaitingKey=room.id+':'+players.length;renderGameRoom();}return;}if(room.game_type==='dice'){if(!s.__diceRendered){s.__diceRendered=true;renderGameRoom();}return;}renderGameRoom();}
function readyCheck(gameType,players,waitStartedAt){const humans=players.filter(p=>!p.is_bot).length,total=players.length,waited=Date.now()-waitStartedAt>BOT_WAIT_MS;if(gameType==='snooker'){if(total>=2)return true;if(humans>=1&&waited)return true;return false;}if(total>=4)return true;if(humans>=2&&waited)return true;if(humans>=1&&waited)return true;return false;}
async function addBot(room){const {data,error}=await window.supabase.from('game_room_players').insert({room_id:room.id,is_bot:true,display_name:BOT_RULES.name,stake_amount:Number(room.stake||500)}).select().single();if(error)throw error;return data;}
async function initWhot(room,players){let all=[...players];if(all.length<2){const bot=await addBot(room);all.push(bot);}const deck=shuffle(createDeck()),pids=all.map(p=>p.user_id||p.id),hands={};let i=0;for(const pid of pids){hands[pid]=deck.slice(i,i+DEFAULT_HAND_SIZE);i+=DEFAULT_HAND_SIZE;}const state={hands,topCard:deck[i++],drawPile:deck.slice(i),turnPlayerId:pids[0],turnOrder:pids,declaredSuit:null,status:'active'};const {error}=await window.supabase.from('game_rooms').update({status:'active',state,started_at:new Date().toISOString()}).eq('id',room.id).eq('status','waiting');if(error)throw error;}
async function initDice(room,players){const pids=players.map(p=>p.user_id||p.id);if(pids.length!==2)return;const state=createDiceState(pids,4);const {error}=await window.supabase.from('game_rooms').update({status:'active',state,started_at:new Date().toISOString()}).eq('id',room.id).eq('status','waiting');if(error)throw error;}
async function initSnooker(room,players){let all=[...players];if(all.length<2){const bot=await addBot(room);all.push(bot);}const state=createSnookerState(all.slice(0,2).map(p=>p.user_id||p.id));const {error}=await window.supabase.from('game_rooms').update({status:'active',state,started_at:new Date().toISOString()}).eq('id',room.id).eq('status','waiting');if(error)throw error;}
async function settleRoom(roomId,winners){const {data,error}=await window.supabase.rpc('game_settle_room',{p_room_id:roomId,p_winner_ids:winners});if(error)console.error('Settlement failed',error);window.state.gameSettlement=data||null;renderGameRoom();}
window.playWhotCard=async function(idx){const s=window.state,sb=window.supabase,{data:room}=await sb.from('game_rooms').select('*').eq('id',s.gameRoomId).single();if(!room||room.status!=='active')return;const st=room.state,pid=s.user.id;if(st.turnPlayerId!==pid)return alert("It's not your turn.");const hand=st.hands[pid]||[],card=hand[idx];let suit=null;if(card?.value===20){suit=prompt('Whot! Declare a suit: '+SUITS.join(', '));if(!SUITS.includes(suit))return alert('Invalid suit.');}try{validateWhotAction(st,pid,idx,suit);}catch(e){return alert(e.message);}st.hands[pid]=hand.filter((_,i)=>i!==idx);st.topCard=card;st.declaredSuit=suit;if(!st.hands[pid].length){await sb.from('game_rooms').update({state:{...st,status:'finished'}}).eq('id',room.id);return settleRoom(room.id,isBotPid(pid)?[]:[pid]);}st.turnPlayerId=nextPlayer(st.turnOrder,pid);await sb.from('game_rooms').update({state:st}).eq('id',room.id);renderGameRoom();};
window.drawWhotCard=async function(){const s=window.state,sb=window.supabase,{data:room}=await sb.from('game_rooms').select('*').eq('id',s.gameRoomId).single();if(!room||room.status!=='active')return;const st=room.state,pid=s.user.id;if(st.turnPlayerId!==pid)return alert("It's not your turn.");if(!st.drawPile?.length)return alert('Draw pile is empty.');st.hands[pid]=[...(st.hands[pid]||[]),st.drawPile.shift()];st.turnPlayerId=nextPlayer(st.turnOrder,pid);await sb.from('game_rooms').update({state:st}).eq('id',room.id);renderGameRoom();};
window.snookerPot=async function(colour){const s=window.state,sb=window.supabase,{data:room}=await sb.from('game_rooms').select('*').eq('id',s.gameRoomId).single();if(!room||room.status!=='active')return;const st=room.state,pid=s.user.id;try{scorePot(st,pid,colour);}catch(e){return alert(e.message);}st.currentPlayerId=st.playerIds.find(id=>id!==pid);await sb.from('game_rooms').update({state:st}).eq('id',room.id);renderGameRoom();};
window.snookerFoul=async function(points){const s=window.state,sb=window.supabase,{data:room}=await sb.from('game_rooms').select('*').eq('id',s.gameRoomId).single();if(!room||room.status!=='active')return;const st=room.state,pid=s.user.id;try{applyFoul(st,pid,points);}catch(e){return alert(e.message);}st.currentPlayerId=st.playerIds.find(id=>id!==pid);await sb.from('game_rooms').update({state:st}).eq('id',room.id);renderGameRoom();};
window.snookerEndFrame=async function(){const s=window.state,sb=window.supabase,{data:room}=await sb.from('game_rooms').select('*').eq('id',s.gameRoomId).single();if(!room||room.status!=='active')return;const st=room.state,result=finishSnooker(st);await sb.from('game_rooms').update({state:{...st,status:'finished'}}).eq('id',room.id);await settleRoom(room.id,result.tie||!result.winner?[]:(isBotPid(result.winner)?[]:[result.winner]));};
function renderGameRoom(){const app=document.querySelector('#app'),s=window.state,c=s.gameRoomCache;if(!app||!c)return;const {room,players}=c;if(room.game_type==='dice'&&room.status==='active'){app.innerHTML=`<div class="wrap"><button class="back" onclick="leaveGameRoom()">← Back</button><div class="panel"><span class="badge">🎲 DICE • ONE DIE • 4 ROLLS</span><h2>Dice Game</h2><p class="muted">Two players. Each player rolls one six-sided die four times. Highest total wins.</p><div class="notice"><b>Rules</b><ul><li>1 die per player.</li><li>4 rolls per player.</li><li>Add all four rolls.</li><li>Highest total wins.</li><li>Equal totals = tie.</li></ul></div><p class="muted">The live die and Roll button are below.</p></div></div>`;return;}const rules=RULES[room.game_type]||{name:room.game_type};let inner='';if(room.status==='waiting')inner=`<div class="panel"><span class="badge">${esc(rules.name)} • WAITING</span><h2>${players.length}/${room.capacity} players joined</h2><p class="muted">Entry ₦${room.stake}. Waiting for the required players.</p>${players.map(p=>`<div class="card"><b>${esc(playerName(players,p.user_id||p.id))}</b></div>`).join('')}<button class="secondary" style="margin-top:14px" onclick="leaveGameRoom()">Cancel & refund</button></div>`;else if(room.status==='active'&&room.game_type==='whot'){const st=room.state,pid=s.user.id,hand=st.hands?.[pid]||[],mine=st.turnPlayerId===pid;inner=`<div class="panel"><span class="badge">🃏 WHOT</span><h3>Top card: ${cardLabel(st.topCard)}</h3><p class="muted">${mine?'Your turn':esc(playerName(players,st.turnPlayerId))+"'s turn"}</p><div class="grid">${hand.map((x,i)=>`<button class="secondary" ${mine?'':'disabled'} onclick="playWhotCard(${i})">${cardLabel(x)}</button>`).join('')}</div>${mine?'<button class="secondary" style="margin-top:10px" onclick="drawWhotCard()">Draw card</button>':''}</div>`;}else if(room.status==='active'&&room.game_type==='snooker'){const st=room.state,pid=s.user.id,mine=st.currentPlayerId===pid;inner=`<div class="panel"><span class="badge">🎱 SNOOKER</span><h3>${mine?'Your turn':"Opponent's turn"}</h3><p class="muted">${Object.entries(st.scores||{}).map(([k,v])=>esc(playerName(players,k))+': '+v).join(' • ')}</p>${mine?`<div class="grid">${Object.keys(BALL_VALUES).map(c=>`<button class="secondary" onclick="snookerPot('${c}')">${c} (+${BALL_VALUES[c]})</button>`).join('')}</div><button class="secondary" style="margin-top:10px" onclick="snookerFoul(4)">Log foul (4pts)</button>`:''}<button class="primary" style="margin-top:10px" onclick="snookerEndFrame()">End frame & settle</button></div>`;}else inner=`<div class="panel"><span class="badge">GAME OVER</span><h2>Round finished</h2><button class="primary" onclick="leaveGameRoom()">Back to Games</button></div>`;app.innerHTML=`<div class="wrap"><button class="back" onclick="leaveGameRoom()">← Back</button>${inner}</div>`;}
function installRenderHook(){if(!window.state||typeof window.render!=='function')return setTimeout(installRenderHook,100);if(window.__fpGamesRenderHookInstalled)return;window.__fpGamesRenderHookInstalled=true;const original=window.render;window.render=async function(){if(window.state?.page==='games'){renderGamesHub();return;}if(window.state?.page==='game_room'){renderGameRoom();return;}return original.apply(this,arguments);};}
installRenderHook();
