/* Realistic game presentation layer for Whot, Dice and Snooker. */
(function(){
'use strict';
const suits={circle:'●',triangle:'▲',cross:'✚',square:'■',star:'★'};
function css(){if(document.getElementById('realGameVisualCss'))return;const s=document.createElement('style');s.id='realGameVisualCss';s.textContent=`
.real-board{margin:16px 0;padding:16px;border-radius:18px;background:linear-gradient(145deg,#0a1420,#111f30);border:1px solid #29415c;box-shadow:0 14px 40px #0006}
.whot-table{display:flex;flex-wrap:wrap;gap:18px;align-items:center;justify-content:center;min-height:190px;background:radial-gradient(circle,#167044,#073c27);border-radius:16px;padding:22px;box-shadow:inset 0 0 0 8px #5b351b,inset 0 0 35px #0008}
.whot-card{width:76px;height:108px;border-radius:9px;background:#fff;color:#111;border:2px solid #ddd;box-shadow:0 7px 12px #0007;display:flex;flex-direction:column;justify-content:space-between;padding:7px;font-weight:900;text-align:center;transform:rotate(var(--r));font-size:15px}.whot-card .big{font-size:30px}.whot-card.back{background:repeating-linear-gradient(45deg,#172b62 0 7px,#274c9a 7px 14px);color:#fff;border-color:#fff}.whot-hand{display:flex;gap:8px;overflow-x:auto;padding:12px 2px 5px;justify-content:center}.whot-hand .whot-card{flex:0 0 68px;height:96px;cursor:pointer}.whot-hand .whot-card:hover{transform:translateY(-10px) rotate(0)}
.dice-table{display:flex;align-items:center;justify-content:center;gap:28px;min-height:210px;background:radial-gradient(circle,#174b32,#06281a);border-radius:16px;padding:30px;box-shadow:inset 0 0 0 8px #5b351b,inset 0 0 35px #0008}.die{width:82px;height:82px;background:linear-gradient(145deg,#fff,#d7d7d7);border-radius:14px;box-shadow:8px 10px 18px #0008,inset 2px 2px 4px #fff;display:grid;grid-template-columns:repeat(3,1fr);grid-template-rows:repeat(3,1fr);padding:10px;transition:transform .12s ease}.die.rolling{animation:diceTumble .72s cubic-bezier(.2,.8,.2,1)}@keyframes diceTumble{0%{transform:translateY(0) rotate(0) rotateX(0) rotateY(0)}20%{transform:translateY(-22px) rotate(90deg) rotateX(90deg) rotateY(35deg)}45%{transform:translateY(-10px) rotate(210deg) rotateX(170deg) rotateY(120deg)}70%{transform:translateY(-4px) rotate(330deg) rotateX(250deg) rotateY(210deg)}100%{transform:translateY(0) rotate(360deg) rotateX(360deg) rotateY(360deg)}}.pip{width:15px;height:15px;background:#111;border-radius:50%;align-self:center;justify-self:center}.d1 .pip:nth-child(1){grid-area:2/2}.d2 .pip:nth-child(1){grid-area:1/1}.d2 .pip:nth-child(2){grid-area:3/3}.d3 .pip:nth-child(1){grid-area:1/1}.d3 .pip:nth-child(2){grid-area:2/2}.d3 .pip:nth-child(3){grid-area:3/3}.d4 .pip:nth-child(1){grid-area:1/1}.d4 .pip:nth-child(2){grid-area:1/3}.d4 .pip:nth-child(3){grid-area:3/1}.d4 .pip:nth-child(4){grid-area:3/3}.d5 .pip:nth-child(1){grid-area:1/1}.d5 .pip:nth-child(2){grid-area:1/3}.d5 .pip:nth-child(3){grid-area:2/2}.d5 .pip:nth-child(4){grid-area:3/1}.d5 .pip:nth-child(5){grid-area:3/3}.d6 .pip:nth-child(1){grid-area:1/1}.d6 .pip:nth-child(2){grid-area:2/1}.d6 .pip:nth-child(3){grid-area:3/1}.d6 .pip:nth-child(4){grid-area:1/3}.d6 .pip:nth-child(5){grid-area:2/3}.d6 .pip:nth-child(6){grid-area:3/3}
.snooker-wrap{background:#3b2113;padding:18px;border-radius:18px;box-shadow:0 14px 35px #0008}.snooker-table{position:relative;aspect-ratio:2/1;max-width:900px;margin:auto;background:radial-gradient(ellipse at center,#0b7540,#07552e 72%,#064326);border:12px solid #6b3e1f;border-radius:7%;box-shadow:inset 0 0 30px #0009,0 5px 12px #0008;overflow:hidden}.pocket{position:absolute;width:30px;height:30px;background:#050505;border-radius:50%}.p1{left:-9px;top:-9px}.p2{right:-9px;top:-9px}.p3{left:-9px;bottom:-9px}.p4{right:-9px;bottom:-9px}.p5{left:50%;top:-9px;transform:translateX(-50%)}.p6{left:50%;bottom:-9px;transform:translateX(-50%)}.ball{position:absolute;width:22px;height:22px;border-radius:50%;box-shadow:inset 5px 4px 5px #fff9,inset -4px -4px 5px #0008,2px 3px 5px #0009}.cue-ball{background:#eee}.red-ball{background:#c92828}.yellow-ball{background:#e6c229}.green-ball{background:#249447}.brown-ball{background:#7b4a24}.blue-ball{background:#287bd6}.pink-ball{background:#e78bb5}.black-ball{background:#111}
@media(max-width:520px){.die{width:68px;height:68px}.pip{width:12px;height:12px}}
`;document.head.appendChild(s)}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function card(c){if(!c)return '';return `<div class="whot-card"><span>${c.value===20?'WHOT':c.value}</span><span class="big">${c.value===20?'★':(suits[c.suit]||c.suit)}</span><small>${c.suit}</small></div>`}
function die(n){n=Math.max(1,Math.min(6,Number(n)||1));return `<div class="die d${n}">${Array.from({length:n},()=>'<i class="pip"></i>').join('')}</div>`}
let lastDiceRollKey='';
function mount(){
 const s=window.state;if(!s||s.page!=='game_room')return;const room=s.gameRoomCache?.room;if(!room||room.status!=='active')return;const panel=document.querySelector('#app .wrap .panel');if(!panel)return;
 let board=panel.querySelector('.real-board');if(!board){board=document.createElement('div');board.className='real-board';panel.insertBefore(board,panel.firstChild)}
 if(room.game_type==='dice'){
   const last=room.state?.pig?.lastRoll;const vals=last?.values||[];const key=last?`${last.playerId}:${last.values.join(',')}:${last.total}`:'none';
   const rolling=key!==lastDiceRollKey&&key!=='none';
   if(key!=='none')lastDiceRollKey=key;
   board.innerHTML=`<div style="text-align:center;font-weight:900;margin-bottom:10px">🎲 LIVE DICE TABLE</div><div class="dice-table">${(vals.length?vals:[1,1]).map(die).join('')}</div><div style="text-align:center;margin-top:10px;font-weight:700">${last?esc(last.values.join(' + ')+' = '+last.total):'Press ROLL DICE to roll'}</div>`;
   if(rolling)setTimeout(()=>board.querySelectorAll('.die').forEach(x=>x.classList.add('rolling')),0);
 }else if(room.game_type==='whot'){const pid=s.user?.id,hand=room.state?.hands?.[pid]||[];board.innerHTML=`<div style="text-align:center;font-weight:900;margin-bottom:10px">🃏 WHOT TABLE</div><div class="whot-table"><div class="whot-card back"><span>WHOT</span><span class="big">★</span><small>DRAW</small></div>${card(room.state?.topCard)}</div><div class="whot-hand">${hand.map(card).join('')}</div>`;}
}
css();setInterval(mount,500);mount();
})();
