/* BetSquad navigation resilience layer. Runs after the core app and game hook. */
(function(){
  const $=s=>document.querySelector(s);
  const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const gameName=t=>({whot:'🃏 Whot',dice:'🎲 Dice',snooker:'🎱 Snooker'}[t]||t||'Game');
  const wait=(p,ms=5000)=>Promise.race([p,new Promise((_,rej)=>setTimeout(()=>rej(new Error('Request timed out. Please try again.')),ms))]);
  let originalGo=null,stack=[];
  function header(){const s=window.state||{},links=['home','games','rooms','rounds','friendly','leaderboard'];return `<header class="top"><div class="brand">Bet<span>Squad</span></div><nav class="nav">${links.map(p=>`<button class="${s.page===p?'active':''}" onclick="go('${p}')">${p[0].toUpperCase()+p.slice(1)}</button>`).join('')}${s.user?`<button class="${s.page==='wallet'?'active':''}" onclick="go('wallet')">Wallet</button>`:''}</nav><div class="top-right">${s.user?`<button class="secondary desktop-only" onclick="signOut()">Sign out</button>`:`<button class="secondary desktop-only" onclick="go('auth')">Login</button>`}</div></header>`;}
  const backButton=()=>`<button class="back" onclick="backFromPage()" style="margin:0 0 14px 0">← Back</button>`;
  function mount(body,nav=true){const app=$('#app');if(app)app.innerHTML=(nav?header():'')+`<main class="wrap">${body}</main>`;}
  async function rooms(){const s=window.state||{},sb=window.supabase;if(!s.user){mount(`${backButton()}<div class="panel"><h2>Rooms</h2><p class="muted">Please sign in to see your games.</p><button class="primary" onclick="go('auth')">Login</button></div>`);return;}mount(`${backButton()}<div class="panel"><h2>Rooms</h2><p class="muted">Loading your unfinished games…</p></div>`);try{const {data:members,error:me}=await wait(sb.from('game_room_players').select('room_id,display_name,is_bot,stake_amount,joined_at').eq('user_id',s.user.id).order('joined_at',{ascending:false}).limit(30));if(me)throw me;const ids=[...new Set((members||[]).map(x=>x.room_id).filter(Boolean))];if(!ids.length){mount(`${backButton()}<div class="panel"><h2>Rooms</h2><p class="muted">You have no unfinished games.</p><button class="primary" onclick="go('games')">Find a game</button></div>`);return;}const {data:rs,error:re}=await wait(sb.from('game_rooms').select('id,game_type,status,capacity,stake,created_at').in('id',ids).in('status',['waiting','active']).order('created_at',{ascending:false}));if(re)throw re;const rows=(rs||[]).map(r=>`<div class="row"><div><b>${gameName(r.game_type)}</b><div class="small">Room ${esc(r.id.slice(0,8))} • ₦${Number(r.stake||0).toFixed(0)} • ${r.status==='active'?'In progress':'Waiting'}</div></div><button class="primary" onclick="resumeGame('${r.id}')">${r.status==='active'?'Resume Game':'Continue'}</button></div>`).join('');mount(`${backButton()}<div class="section"><h2>Rooms</h2><p class="muted">Continue a game you already joined. Resuming does not charge another stake.</p></div>${rows?`<div class="panel">${rows}</div>`:`<div class="panel"><h3>No unfinished games</h3><button class="primary" onclick="go('games')">Find a game</button></div>`}`);}catch(e){mount(`${backButton()}<div class="panel"><h2>Rooms</h2><p class="muted">We could not load your rooms yet.</p><p class="small">${esc(e.message||e)}</p><button class="primary" onclick="go('rooms')">Try again</button></div>`);}}
  async function wallet(){const s=window.state||{},sb=window.supabase;if(!s.user){mount(`${backButton()}<div class="panel"><h2>Wallet</h2><p class="muted">Please sign in to open your wallet.</p><button class="primary" onclick="go('auth')">Login</button></div>`);return;}mount(`${backButton()}<div class="panel"><h2>Wallet</h2><p class="muted">Loading wallet…</p></div>`);try{const [{data:w,error:we},{data:reqs,error:re}]=await wait(Promise.all([sb.from('game_wallets').select('points,diamonds,cash_balance').eq('user_id',s.user.id).single(),sb.from('withdrawal_requests').select('id,amount,status,created_at').eq('user_id',s.user.id).order('created_at',{ascending:false}).limit(20)]));if(we&&we.code!=='PGRST116')throw we;if(re)throw re;mount(`${backButton()}<div class="section"><h2>Wallet</h2></div><div class="grid"><div class="card"><b>Cash balance</b><p style="font-size:22px">₦${Number(w?.cash_balance||0).toFixed(2)}</p></div><div class="card"><b>Points</b><p style="font-size:22px">${w?.points||0}</p></div><div class="card"><b>💎 Diamonds</b><p style="font-size:22px">${w?.diamonds||0}</p></div></div><div class="panel" style="margin-top:16px"><h3>Withdrawal</h3><input id="wdAmount" type="number" min="1" placeholder="Amount"><input id="wdDestination" placeholder="Bank / Opay / Moniepoint details" style="margin-top:8px"><button class="primary" style="margin-top:10px" onclick="requestWithdrawal()">Request withdrawal</button><h4>Your requests</h4>${(reqs||[]).map(r=>`<div class="row"><span>₦${Number(r.amount).toFixed(2)}</span><span class="badge">${esc(String(r.status).toUpperCase())}</span></div>`).join('')||'<p class="muted">No withdrawal requests yet.</p>'}</div>`);}catch(e){mount(`${backButton()}<div class="panel"><h2>Wallet</h2><p class="muted">Wallet could not be loaded.</p><p class="small">${esc(e.message||e)}</p><button class="primary" onclick="go('wallet')">Try again</button></div>`);}}
  async function leaderboard(){const sb=window.supabase;mount(`${backButton()}<div class="panel"><h2>Leaderboard</h2><p class="muted">Loading leaderboard…</p></div>`);try{const {data:round}=await wait(sb.from('rounds').select('*').eq('status','open').order('created_at',{ascending:false}).limit(1).maybeSingle());let rows=[];if(round?.id){const {data,error}=await wait(sb.from('entries').select('user_id,total_points,profiles(display_name)').eq('round_id',round.id).order('total_points',{ascending:false}));if(error)throw error;rows=data||[];}mount(`${backButton()}<div class="section"><h2>Leaderboard</h2><span class="badge">🔴 LIVE • ${rows.length} entrants</span></div><div class="panel"><table class="table"><tr><th>#</th><th>Player</th><th>Points</th><th>Prize</th></tr>${rows.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.profiles?.display_name||'Player')}</td><td>${r.total_points||0}</td><td>${i===0?'🏆 Cash':i===1?'🏆 Cash':i===2?'💎 Diamonds':'—'}</td></tr>`).join('')||'<tr><td colspan="4">No teams submitted.</td></tr>'}</table></div>`);}catch(e){mount(`${backButton()}<div class="panel"><h2>Leaderboard</h2><p class="muted">Leaderboard could not be loaded.</p><button class="primary" onclick="go('leaderboard')">Try again</button></div>`);}}
  window.backFromPage=function(){const p=stack.pop()||'home';if(originalGo)originalGo(p);else{window.state.page=p;window.render?.();}};
  function addBack(){if(!$('#app')||window.state?.page==='home')return;const main=$('#app .wrap');if(main&&!main.querySelector('.back'))main.insertAdjacentHTML('afterbegin',backButton());}
  function install(){if(typeof window.go!=='function'||typeof window.render!=='function')return setTimeout(install,100);if(window.__betSquadNavigationResilience)return;window.__betSquadNavigationResilience=true;originalGo=window.go;window.go=function(page){const current=window.state?.page;if(current&&current!==page)stack.push(current);window.state.page=page;window.state.menuOpen=false;if(page==='rooms'){rooms();return;}if(page==='wallet'){wallet();return;}if(page==='leaderboard'){leaderboard();return;}try{const r=originalGo(page);Promise.resolve(r).catch(e=>{console.error('Navigation failed',e);mount(`${backButton()}<div class="panel"><h2>Page could not be loaded</h2><p class="muted">${esc(e.message||e)}</p><button class="primary" onclick="backFromPage()">← Back</button></div>`);});setTimeout(addBack,150);}catch(e){console.error('Navigation failed',e);mount(`${backButton()}<div class="panel"><h2>Page could not be loaded</h2><p class="muted">${esc(e.message||e)}</p></div>`);}};const oldResume=window.resumeGame;if(oldResume){window.resumeGame=async function(id){try{return await oldResume(id);}catch(e){alert('Resume failed: '+(e.message||e));window.go('rooms');}};}setTimeout(addBack,250);}
  install();
})();
