(() => {
  'use strict';
  const LOBBY='betsquad-online-games';
  let channel=null, currentChallenge=null;
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const sb=()=>window.supabase;
  const me=()=>window.state?.user?.id;
  const name=()=>window.state?.user?.user_metadata?.name||window.state?.user?.email?.split('@')[0]||'Player';
  const ensure=()=>{if(!sb()||!me())return null;if(channel)return channel;channel=sb().channel(LOBBY,{config:{presence:{key:me()},broadcast:{self:false}}});channel.on('presence',{event:'sync'},renderOnline);channel.on('broadcast',{event:'game-challenge',payload:async p=>{if(p?.to!==me())return;await showChallenge(p)}});channel.on('broadcast',{event:'game-room-ready',payload:p=>{if(p?.to!==me()||!p.roomId)return;joinReadyRoom(p.roomId,p.gameType)}});channel.subscribe(async status=>{if(status==='SUBSCRIBED'){await channel.track({user_id:me(),display_name:name(),online_at:new Date().toISOString()});renderOnline()}});return channel};
  function peers(){if(!channel)return[];const out=[];const all=channel.presenceState();Object.keys(all).forEach(uid=>{if(uid===me())return;const p=all[uid]?.[0];if(p)out.push(p)});return out}
  function renderOnline(){const box=document.querySelector('#onlineGamePlayers');if(!box)return;const ps=peers();box.innerHTML=ps.length?ps.map(p=>`<div class="online-player"><span><i></i>${esc(p.display_name||'Player')}</span><button data-user="${esc(p.user_id)}" data-name="${esc(p.display_name||'Player')}">Challenge</button></div>`).join(''):'<p class="muted">No other players are online right now.</p>';box.querySelectorAll('button').forEach(b=>b.onclick=()=>challenge(b.dataset.user,b.dataset.name));}
  async function challenge(to,toName){const type=window.state.gameType||'whot';const choices=[500,1000,2000];const raw=prompt(`Stake to play ${type}: ₦500, ₦1000 or ₦2000`,String(choices[0]));const stake=Number(raw);if(!choices.includes(stake))return alert('Choose ₦500, ₦1000 or ₦2000.');const {data,error}=await sb().from('game_challenges').insert({game_type:type,stake,challenger_id:me(),challenged_id:to,status:'pending'}).select().single();if(error)return alert('Challenge failed: '+error.message);ensure()?.send({type:'broadcast',event:'game-challenge',payload:{to,challengeId:data.id,from:me(),fromName:name(),gameType:type,stake}});alert(`Challenge sent to ${toName}. Waiting for acceptance.`);}
  async function showChallenge(p){if(currentChallenge)return;currentChallenge=p;const ok=confirm(`${p.fromName} wants to play ${p.gameType} for ₦${p.stake}.\n\nAccept the challenge?`);currentChallenge=null;if(!ok){await sb().from('game_challenges').update({status:'rejected',responded_at:new Date().toISOString()}).eq('id',p.challengeId).eq('challenged_id',me());return}const {data:challenge,error}=await sb().from('game_challenges').update({status:'accepted',responded_at:new Date().toISOString()}).eq('id',p.challengeId).eq('challenged_id',me()).eq('status','pending').select().single();if(error||!challenge)return alert('This challenge is no longer available.');const roomPayload={game_code:p.gameType,game_type:p.gameType,room_type:'private',entry_fee:p.stake,stake:p.stake,max_players:2,capacity:2,created_by:me(),creator_id:me(),bot_allowed:false,state:{}};const {data:room,error:re}=await sb().from('game_rooms').insert(roomPayload).select().single();if(re)return alert('Could not create the game room: '+re.message);await sb().from('game_room_players').insert({room_id:room.id,user_id:me(),display_name:name(),stake_amount:p.stake,is_bot:false});await sb().from('game_challenges').update({room_id:room.id}).eq('id',p.challengeId);const debit=await sb().rpc('game_debit_stake',{p_amount:p.stake});if(debit.error||!debit.data){await sb().from('game_room_players').delete().eq('room_id',room.id).eq('user_id',me());await sb().from('game_challenges').update({status:'cancelled'}).eq('id',p.challengeId);return alert('You do not have enough balance for this stake.');}channel.send({type:'broadcast',event:'game-room-ready',payload:{to:p.from,roomId:room.id,gameType:p.gameType,stake:p.stake,challengeId:p.challengeId}});enterRoom(room.id,p.gameType);}
  async function joinReadyRoom(roomId,type){const {data:room}=await sb().from('game_rooms').select('*').eq('id',roomId).single();if(!room)return;const {data:existing}=await sb().from('game_room_players').select('id').eq('room_id',roomId).eq('user_id',me()).maybeSingle();if(!existing){const {error}=await sb().from('game_room_players').insert({room_id:roomId,user_id:me(),display_name:name(),stake_amount:Number(room.stake),is_bot:false});if(error)return alert('Could not join the accepted game: '+error.message)}const debit=await sb().rpc('game_debit_stake',{p_amount:Number(room.stake)});if(debit.error||!debit.data){await sb().rpc('game_refund_stake',{p_room_id:roomId});return alert('You do not have enough balance for this stake.');}enterRoom(roomId,type)}
  function enterRoom(roomId,type){window.state.gameType=type;window.state.gameRoomId=roomId;window.state.gameWaitStarted=Date.now();window.state.gameRoomCache=null;window.state.gameSettlement=null;window.state.page='game_room';window.render();if(typeof window.startGamePolling==='function')window.startGamePolling();}
  function mount(){const app=document.querySelector('#app');if(!app||window.state?.page!=='games'||!me()||!sb())return;ensure();let box=document.querySelector('#onlineGameMatchmaking');if(box)return;box=document.createElement('div');box.id='onlineGameMatchmaking';box.className='panel';box.innerHTML='<h3>🟢 Players online</h3><p class="muted">Choose a player and challenge them. Both players choose the stake before the game starts.</p><div id="onlineGamePlayers"></div>';app.appendChild(box);const st=document.createElement('style');st.textContent='.online-player{display:flex;justify-content:space-between;align-items:center;padding:9px 0;border-bottom:1px solid rgba(255,255,255,.1)}.online-player span{display:flex;align-items:center;gap:8px}.online-player i{width:9px;height:9px;border-radius:50%;background:#20a464;display:inline-block}.online-player button{border:0;border-radius:8px;padding:8px 12px;font-weight:700;cursor:pointer}';document.head.appendChild(st);renderOnline()}
  const oldPlay=window.playGame;window.playGame=async function(type){window.state.gameType=type;if(oldPlay)await oldPlay(type)};
  const mo=new MutationObserver(mount);mo.observe(document.documentElement,{childList:true,subtree:true});setInterval(mount,1000);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();