(() => {
  'use strict';
  const LOBBY='betsquad-online-games';
  let channel=null,currentChallenge=null;
  const sb=()=>window.supabase, me=()=>window.state?.user?.id;
  const displayName=()=>window.state?.user?.user_metadata?.name||window.state?.user?.email?.split('@')[0]||'Player';
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  function ensure(){if(!sb()||!me())return null;if(channel)return channel;channel=sb().channel(LOBBY,{config:{presence:{key:me()},broadcast:{self:false}}});channel.on('presence',{event:'sync'},renderOnline);channel.on('broadcast',{event:'game-challenge'},async({payload})=>{if(payload?.to===me())await showChallenge(payload)});channel.on('broadcast',{event:'challenge-result'},({payload})=>{if(payload?.to!==me())return;if(payload.status==='rejected')alert('Your game request was rejected.');if(payload.status==='accepted'&&payload.roomId)enterRoom(payload.roomId,payload.gameType)});channel.subscribe(async status=>{if(status==='SUBSCRIBED'){await channel.track({user_id:me(),display_name:displayName(),online_at:new Date().toISOString()});renderOnline()}});return channel}
  function peers(){const c=ensure();if(!c)return[];const all=c.presenceState(),out=[];Object.keys(all).forEach(k=>{if(k===me())return;const p=all[k]?.[0];if(p?.user_id)out.push(p)});return out}
  function renderOnline(){const box=document.querySelector('#onlineGamePlayers');if(!box)return;const ps=peers();box.innerHTML=ps.length?ps.map(p=>`<div class="online-player"><span><i></i>${esc(p.display_name||'Player')}</span><button data-user="${esc(p.user_id)}" data-name="${esc(p.display_name||'Player')}">Request to play</button></div>`).join(''):'<p class="muted">No other players are online right now.</p>';box.querySelectorAll('button').forEach(b=>b.onclick=()=>sendChallenge(b.dataset.user,b.dataset.name));}
  async function sendChallenge(to,toName){const s=window.state;if(!s.gameRoomId)return alert('Find a room first.');const {data:room,error:re}=await sb().from('game_rooms').select('id,game_type,stake,status,capacity').eq('id',s.gameRoomId).single();if(re||!room||room.status!=='waiting')return alert('This room is no longer waiting for a player.');const stake=Number(room.stake||500);const {data,error}=await sb().from('game_challenges').insert({game_type:room.game_type,stake,challenger_id:me(),challenged_id:to,status:'pending',room_id:room.id}).select().single();if(error)return alert('Request failed: '+error.message);ensure().send({type:'broadcast',event:'game-challenge',payload:{to,challengeId:data.id,from:me(),fromName:displayName(),gameType:room.game_type,stake,roomId:room.id}});alert(`Request sent to ${toName} for ₦${stake}. Waiting for acceptance.`);}
  async function showChallenge(p){if(currentChallenge)return;currentChallenge=p;const ok=confirm(`${p.fromName} wants to play ${p.gameType} for ₦${p.stake}.\n\nAccept and stake ₦${p.stake} to join?`);currentChallenge=null;if(!ok){await sb().from('game_challenges').update({status:'rejected',responded_at:new Date().toISOString()}).eq('id',p.challengeId).eq('challenged_id',me()).eq('status','pending');ensure().send({type:'broadcast',event:'challenge-result',payload:{to:p.from,status:'rejected'}});return;}const {data:challenge,error}=await sb().from('game_challenges').update({status:'accepted',responded_at:new Date().toISOString()}).eq('id',p.challengeId).eq('challenged_id',me()).eq('status','pending').select().single();if(error||!challenge)return alert('This request is no longer available.');const {data:room,error:re}=await sb().from('game_rooms').select('id,game_type,stake,status,capacity').eq('id',p.roomId).single();if(re||!room||room.status!=='waiting')return alert('The room has already started or closed.');const debit=await sb().rpc('game_debit_stake',{p_amount:Number(room.stake)});if(debit.error||!debit.data){await sb().from('game_challenges').update({status:'cancelled'}).eq('id',p.challengeId);return alert(`You need ₦${room.stake} available in your wallet to join.`);}const {error:je}=await sb().from('game_room_players').insert({room_id:room.id,user_id:me(),display_name:displayName(),stake_amount:Number(room.stake),is_bot:false});if(je){await sb().rpc('game_refund_stake',{p_room_id:room.id});return alert('Could not join the game: '+je.message);}await sb().from('game_challenges').update({room_id:room.id}).eq('id',p.challengeId);ensure().send({type:'broadcast',event:'challenge-result',payload:{to:p.from,status:'accepted',roomId:room.id,gameType:room.game_type}});enterRoom(room.id,room.game_type);}
  function enterRoom(roomId,type){window.state.gameType=type;window.state.gameRoomId=roomId;window.state.gameWaitStarted=Date.now()-16000;window.state.gameRoomCache=null;window.state.gameSettlement=null;window.state.page='game_room';window.render();}
  function mountWaiting(){const s=window.state,app=document.querySelector('#app');if(!app||s?.page!=='game_room'||!s.gameRoomId||!me())return;const room=s.gameRoomCache?.room;if(!room||room.status!=='waiting')return;if(document.querySelector('#findOnlineGameButton'))return;const leave=document.querySelector('[onclick*="leaveGameRoom"]');const host=leave?.parentElement||app.querySelector('.actions')||app.querySelector('.wrap');if(!host)return;const b=document.createElement('button');b.id='findOnlineGameButton';b.className='primary';b.textContent='🟢 Find an online player';b.style.marginLeft='8px';b.onclick=()=>{ensure();showOnlinePicker(room)};host.appendChild(b);}
  function showOnlinePicker(room){let modal=document.querySelector('#onlineGamePicker');if(modal)modal.remove();modal=document.createElement('div');modal.id='onlineGamePicker';modal.style.cssText='position:fixed;inset:0;z-index:100010;background:rgba(0,0,0,.7);display:flex;align-items:center;justify-content:center;padding:16px';modal.innerHTML=`<div style="width:min(520px,100%);max-height:80vh;overflow:auto;background:#0d1b2e;color:#fff;border:1px solid #29415c;border-radius:16px;padding:18px"><h3 style="margin-top:0">🟢 Online players</h3><p class="muted">Game: ${esc(room.game_type)} · Stake: ₦${Number(room.stake||500)}</p><div id="onlineGamePlayers"></div><button class="secondary" id="closeOnlinePicker" style="margin-top:12px;width:100%">Cancel</button></div>`;document.body.appendChild(modal);modal.querySelector('#closeOnlinePicker').onclick=()=>modal.remove();renderOnline();}
  function gamesHub(){const app=document.querySelector('#app');if(!app||window.state?.page!=='games'||!me())return;ensure();let box=document.querySelector('#onlineGameMatchmaking');if(box)return;box=document.createElement('div');box.id='onlineGameMatchmaking';box.className='panel';box.innerHTML='<h3>🟢 Players online</h3><p class="muted">Players currently online can be challenged for the selected game.</p><div id="onlineGamePlayers"></div>';app.appendChild(box);renderOnline();}
  function run(){ensure();gamesHub();mountWaiting();}
  new MutationObserver(run).observe(document.documentElement,{childList:true,subtree:true});setInterval(run,1000);run();
})();