/* Personal Wallet dashboard: private balance/history and automatic transaction refresh. */
(function(){
  'use strict';
  let wrapped=false,refreshTimer=null,channel=null;
  function dashboardHtml(){return '<section id="fpPersonalDashboard" class="panel" style="display:block!important;visibility:visible!important;opacity:1!important;position:relative;z-index:30;margin:16px auto;padding:18px;border:2px solid rgba(82,224,145,.45);background:#0b1d31;scroll-margin-top:90px"><span class="badge">PRIVATE — MY DASHBOARD</span><h2 style="margin:8px 0">My Personal Dashboard</h2><p class="small muted">Only you can see your wallet, deposits, withdrawals and stake information.</p><div class="notice" style="margin-top:12px"><b>OPay deposit account</b><br>Account number: <strong style="font-size:22px;letter-spacing:1px">9152926691</strong><br><button id="fpDashCopyAccount" class="secondary" style="margin-top:8px">COPY ACCOUNT NUMBER</button></div><div id="fpDashBody" class="notice" style="margin-top:12px">Loading your personal account...</div><div id="fpWithdrawalBox" class="notice" style="margin-top:12px"><h3 style="margin-top:0">Request Withdrawal</h3><p class="small muted">Enter the amount you want to withdraw and the bank/account where you want it sent.</p><input id="fpWithdrawAmount" type="number" min="1" step="0.01" placeholder="Amount"><input id="fpWithdrawDestination" placeholder="Bank + account number" style="margin-top:8px"><button id="fpWithdrawButton" class="primary" style="width:100%;margin-top:8px">REQUEST WITHDRAWAL</button></div></section>';}
  async function loadDashboard(){
    const s=window.state,sb=window.supabase,box=document.getElementById('fpPersonalDashboard');
    if(!box||!s?.user||!sb||s.page!=='wallet')return;
    const uid=s.user.id;
    try{
      const [w,d,wd]=await Promise.all([
        sb.from('game_wallets').select('cash_balance,points,diamonds').eq('user_id',uid).maybeSingle(),
        sb.from('deposit_requests').select('amount,status,reference,created_at').eq('user_id',uid).order('created_at',{ascending:false}).limit(50),
        sb.from('withdrawal_requests').select('amount,status,destination,created_at').eq('user_id',uid).order('created_at',{ascending:false}).limit(50)
      ]);
      const deposits=d.data||[],withdrawals=wd.data||[],fmt=n=>Number(n||0).toLocaleString();
      const pending=withdrawals.find(x=>String(x.status).toLowerCase()==='pending');
      box.querySelector('#fpDashBody').innerHTML='<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:8px"><div><span class="small muted">CASH BALANCE</span><br><strong style="font-size:22px">₦'+fmt(w.data?.cash_balance)+'</strong></div><div><span class="small muted">POINTS</span><br><strong style="font-size:22px">'+fmt(w.data?.points)+'</strong></div><div><span class="small muted">DIAMONDS</span><br><strong style="font-size:22px">'+fmt(w.data?.diamonds)+'</strong></div></div>'+(pending?'<div class="notice" style="margin-top:12px"><b>WITHDRAWAL PENDING</b><br>'+fmt(pending.amount)+' — waiting for Admin approval.</div>':'')+'<hr style="border:0;border-top:1px solid rgba(255,255,255,.1);margin:14px 0"><h3>Deposit history</h3>'+(deposits.length?deposits.map(x=>'<div class="row"><span>₦'+fmt(x.amount)+' — '+x.status+(x.reference?' — '+x.reference:'')+'</span><span class="small">'+new Date(x.created_at).toLocaleString()+'</span></div>').join(''):'<p class="muted">No deposits yet.</p>')+'<h3 style="margin-top:16px">Withdrawal history</h3>'+(withdrawals.length?withdrawals.map(x=>'<div class="row"><span>₦'+fmt(x.amount)+' — '+x.status+'</span><span class="small">'+new Date(x.created_at).toLocaleString()+'</span></div>').join(''):'<p class="muted">No withdrawals yet.</p>');
      const form=box.querySelector('#fpWithdrawalBox');
      if(pending){form.innerHTML='<h3 style="margin-top:0">Withdrawal request submitted</h3><p class="small muted">Your ₦'+fmt(pending.amount)+' withdrawal is pending Admin approval. You cannot submit another withdrawal until this one is resolved.</p>';}
      else if(!form.querySelector('#fpWithdrawButton')){form.innerHTML='<h3 style="margin-top:0">Request Withdrawal</h3><p class="small muted">Enter the amount you want to withdraw and the bank/account where you want it sent.</p><input id="fpWithdrawAmount" type="number" min="1" step="0.01" placeholder="Amount"><input id="fpWithdrawDestination" placeholder="Bank + account number" style="margin-top:8px"><button id="fpWithdrawButton" class="primary" style="width:100%;margin-top:8px">REQUEST WITHDRAWAL</button>';bindWithdraw(box);}
    }catch(e){console.error('FootballPoints dashboard refresh',e);}
  }
  function bindWithdraw(box){const btn=box.querySelector('#fpWithdrawButton');if(!btn)return;btn.onclick=async()=>{const amount=Number(box.querySelector('#fpWithdrawAmount').value),destination=box.querySelector('#fpWithdrawDestination').value.trim();if(!amount||amount<=0)return alert('Enter a valid withdrawal amount.');if(!destination)return alert('Enter the bank/account destination.');btn.disabled=true;const r=await window.supabase.rpc('create_withdrawal_request',{p_amount:amount,p_destination:destination});if(r.error){btn.disabled=false;return alert(r.error.message);}alert('Withdrawal request sent to Admin.');await loadDashboard();};}
  async function mount(){const s=window.state,sb=window.supabase;if(!s||!sb||!s.user||s.page!=='wallet')return;const host=document.querySelector('main.wrap');if(!host)return;const uid=s.user.id;let box=document.getElementById('fpPersonalDashboard');if(!box||box.parentElement!==host||box.dataset.uid!==uid){if(box)box.remove();host.insertAdjacentHTML('afterbegin',dashboardHtml());box=document.getElementById('fpPersonalDashboard');box.dataset.uid=uid;box.querySelector('#fpDashCopyAccount').onclick=async()=>{try{await navigator.clipboard.writeText('9152926691');box.querySelector('#fpDashCopyAccount').textContent='COPIED ✓';}catch(e){alert('Account number: 9152926691')}};bindWithdraw(box);}await loadDashboard();if(refreshTimer)clearInterval(refreshTimer);refreshTimer=setInterval(()=>{if(window.state?.page==='wallet')loadDashboard();},3000);if(channel)sb.removeChannel(channel);channel=sb.channel('wallet-balance-'+uid).on('postgres_changes',{event:'*',schema:'public',table:'game_wallets',filter:'user_id=eq.'+uid},()=>loadDashboard()).subscribe();}
  function install(){if(wrapped||typeof window.render!=='function')return false;const original=window.render;window.render=async function(){const result=await original.apply(this,arguments);if(window.state?.page==='wallet')setTimeout(mount,0);return result;};wrapped=true;mount();return true;}
  const timer=setInterval(()=>{if(install())clearInterval(timer);else if(window.state?.page==='wallet')mount();},100);new MutationObserver(()=>{if(window.state?.page==='wallet')setTimeout(mount,50)}).observe(document.body,{childList:true,subtree:true});
})();