/* Personal dashboard + admin stake entry + public stake leaderboard. */
(function(){
'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function sb(){return window.supabase||window.supabaseClient||window._supabase}
async function wallet(){const s=sb();if(!s)return null;const {data,error}=await s.from('game_wallets').select('cash_balance,points,diamonds').eq('user_id',window.state.user.id).maybeSingle();return error?null:data}
async function renderPersonal(){
 if(!window.state?.user||window.state.page!=='wallet')return;
 const s=sb();if(!s)return;
 let host=document.getElementById('fpPersonalDashboard');if(!host){host=document.createElement('section');host.id='fpPersonalDashboard';host.className='panel';host.style.cssText='margin:14px auto;max-width:1180px;border:1px solid rgba(82,224,145,.3);';const main=document.querySelector('main.wrap');if(main)main.insertBefore(host,main.firstChild);else return;}
 const [{data:deps=[]},{data:wds=[]},{data:stakes=[]},bal]=await Promise.all([
  s.from('deposit_requests').select('id,amount,status,reference,created_at,processed_at').eq('user_id',window.state.user.id).order('created_at',{ascending:false}).limit(25),
  s.from('withdrawal_requests').select('id,amount,status,destination,created_at,processed_at').eq('user_id',window.state.user.id).order('created_at',{ascending:false}).limit(25),
  s.from('stake_records').select('id,stake_amount,status,room_id,placed_at').eq('user_id',window.state.user.id).order('placed_at',{ascending:false}).limit(25),
  wallet()
 ]);
 const active=(stakes||[]).filter(x=>x.status==='active').reduce((a,x)=>a+Number(x.stake_amount||0),0);
 host.innerHTML='<div style="display:flex;justify-content:space-between;gap:10px;align-items:center;flex-wrap:wrap"><div><span class="badge">MY PERSONAL DASHBOARD</span><h2 style="margin:8px 0 3px">My Wallet & Activity</h2><p class="muted" style="margin:0">Only you can see this dashboard.</p></div><button class="secondary" id="fpRefreshPersonal">REFRESH</button></div><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:10px;margin-top:14px"><div class="notice"><b>Wallet balance</b><div style="font-size:22px;font-weight:800">'+Number(bal?.cash_balance||0).toLocaleString()+'</div></div><div class="notice"><b>Active stake</b><div style="font-size:22px;font-weight:800">'+active.toLocaleString()+'</div></div><div class="notice"><b>Deposits</b><div style="font-size:22px;font-weight:800">'+(deps||[]).length+'</div></div><div class="notice"><b>Withdrawals</b><div style="font-size:22px;font-weight:800">'+(wds||[]).length+'</div></div></div><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:12px;margin-top:14px"><div><h3>Deposit history</h3>'+(deps?.length?deps.map(x=>'<div class="notice" style="margin:6px 0">'+Number(x.amount).toLocaleString()+' · <b>'+esc(x.status)+'</b><br><small>'+new Date(x.created_at).toLocaleString()+'</small></div>').join(''):'<p class="muted">No deposits yet.</p>')+'</div><div><h3>Withdrawal history</h3>'+(wds?.length?wds.map(x=>'<div class="notice" style="margin:6px 0">'+Number(x.amount).toLocaleString()+' · <b>'+esc(x.status)+'</b><br><small>'+new Date(x.created_at).toLocaleString()+'</small></div>').join(''):'<p class="muted">No withdrawals yet.</p>')+'</div></div><div style="margin-top:12px"><h3>My stake history</h3>'+(stakes?.length?stakes.map(x=>'<div class="notice" style="margin:6px 0">Stake: <b>'+Number(x.stake_amount).toLocaleString()+'</b> · '+esc(x.status)+'<br><small>'+new Date(x.placed_at).toLocaleString()+'</small></div>').join(''):'<p class="muted">No stakes recorded yet.</p>')+'</div>';
 host.querySelector('#fpRefreshPersonal').onclick=renderPersonal;
}
async function adminPanel(){
 if(!window.state?.user||window.state.page!=='admin'||!window.state.isAdmin)return;
 const s=sb();if(!s)return;let host=document.getElementById('fpAdminStakePanel');if(host)return;
 host=document.createElement('section');host.id='fpAdminStakePanel';host.className='panel';host.style.cssText='margin:14px auto;max-width:1180px;border:1px solid rgba(255,196,45,.35);';
 host.innerHTML='<span class="badge">ADMIN STAKE CONTROL</span><h2 style="margin:8px 0">Enter each staker amount</h2><p class="muted">Enter the amount actually paid by each player, then press UPDATE. The amount is saved to that player’s personal dashboard and included in the stake leaderboard.</p><div id="fpAdminStakeRows">Loading players…</div>';
 const main=document.querySelector('main.wrap');if(main)main.insertBefore(host,main.firstChild);else return;
 const {data:profiles,error}=await s.from('profiles').select('id,display_name,bet_name,username').order('display_name');if(error){host.querySelector('#fpAdminStakeRows').textContent=error.message;return}
 host.querySelector('#fpAdminStakeRows').innerHTML=(profiles||[]).map(p=>'<div class="notice" style="display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin:7px 0"><b style="min-width:180px">'+esc(p.display_name||p.bet_name||p.username||'Player')+'</b><input inputmode="decimal" type="number" min="0" step="0.01" placeholder="Stake amount" data-user="'+p.id+'" style="max-width:180px"><input type="text" placeholder="Room ID (optional)" data-room="'+p.id+'" style="max-width:240px"><button class="primary fpStakeUpdate" data-user="'+p.id+'">UPDATE</button><span class="small" data-msg="'+p.id+'"></span></div>').join('');
 host.querySelectorAll('.fpStakeUpdate').forEach(btn=>btn.onclick=async()=>{const id=btn.dataset.user,amt=Number(host.querySelector('input[data-user="'+id+'"]').value),room=(host.querySelector('input[data-room="'+id+'"]').value||'').trim()||null;if(!Number.isFinite(amt)||amt<0){alert('Enter a valid stake amount.');return}btn.disabled=true;const {error}=await s.rpc('admin_set_stake',{p_user_id:id,p_amount:amt,p_room_id:room});btn.disabled=false;host.querySelector('[data-msg="'+id+'"]').textContent=error?('Error: '+error.message):'Updated ✓';});
}
async function leaderboard(){
 if(window.state?.page!=='leaderboard')return;const s=sb();if(!s)return;let host=document.getElementById('fpStakeLeaderboard');if(!host){host=document.createElement('section');host.id='fpStakeLeaderboard';host.className='panel';host.style.cssText='margin:14px auto;max-width:1180px;';const main=document.querySelector('main.wrap');if(main)main.insertBefore(host,main.firstChild);else return;}
 const {data,error}=await s.from('stake_leaderboard').select('player_name,stake_amount,status,placed_at').order('stake_amount',{ascending:false}).limit(100);if(error){host.innerHTML='<span class="badge">STAKE LEADERBOARD</span><p class="muted">Unable to load stake totals right now.</p>';return}const total=(data||[]).reduce((a,x)=>a+Number(x.stake_amount||0),0);host.innerHTML='<span class="badge">STAKE LEADERBOARD</span><h2 style="margin:8px 0">Stakers & Total Pool</h2><div class="notice"><b>Total amount staked:</b> '+total.toLocaleString()+'</div><div style="margin-top:10px">'+(data||[]).map((x,i)=>'<div class="notice" style="display:flex;justify-content:space-between;gap:10px;margin:6px 0"><span>#'+(i+1)+' '+esc(x.player_name)+'</span><b>'+Number(x.stake_amount).toLocaleString()+'</b></div>').join('')+'</div>';
}
function interceptNav(){document.addEventListener('click',e=>{const b=e.target.closest?.('button,a');if(!b||!window.state?.user)return;const t=(b.textContent||'').trim().toLowerCase();if(t==='deposit'||t==='withdraw'||t==='withdrawal'){if(window.state.page!=='wallet'){window.state.page='wallet';window.render?.()}setTimeout(renderPersonal,250)}});}
function boot(){interceptNav();setInterval(()=>{renderPersonal();adminPanel();leaderboard()},1200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
