/* FINAL room match + 7-player flow + immediate match entry. */
(function(){
  const R=()=>window.roomFlow;
  const esc=v=>String(v==null?'':v).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const norm=v=>String(v||'').toLowerCase().replace(/[^a-z0-9]/g,'');
  const same=(a,b)=>{const x=norm(a),y=norm(b);return x===y||x.indexOf(y)>=0||y.indexOf(x)>=0;};
  const limits={GK:1,DEF:2,MID:3,ST:1};
  const pos=v=>{const p=String(v||'').toUpperCase();if(['GK','G','GKP','GOALKEEPER'].includes(p))return 'GK';if(['DEF','DF','D','DEFENDER'].includes(p))return 'DEF';if(['MID','MF','M','MIDFIELDER'].includes(p))return 'MID';if(['ST','FW','F','CF','FORWARD','STRIKER'].includes(p))return 'ST';return p;};
  const count=(mine,p)=>mine.filter(x=>pos(x.slot_position||x.players?.position)===p).length;
  const getState=()=>window.state||{};
  const leader=()=>{const r=R()?.room,s=getState();return !!(r&&s.user&&String(r.creator_id)===String(s.user.id));};
  const ngTime=d=>new Intl.DateTimeFormat('en-NG',{timeZone:'Africa/Lagos',weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',hour12:true}).format(new Date(d));
  const day=d=>new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Lagos',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(d));
  async function fixtures(){const q=await supabase.from('upcoming_fixtures').select('id,home_team,away_team,kickoff_at,status').gte('kickoff_at',new Date(Date.now()-2*3600000).toISOString()).lte('kickoff_at',new Date(Date.now()+48*3600000).toISOString()).order('kickoff_at').limit(100);if(q.error)throw q.error;return q.data||[];}
  async function playersFor(f){const q=await supabase.from('players').select('id,name,club,position,photo_url').eq('active',true).order('name');if(q.error)throw q.error;return (q.data||[]).filter(p=>[f.home_team,f.away_team].some(t=>same(p.club,t)));}
  window.startRoomMatch=async function(){if(!leader())return alert('Only the room leader can choose the match.');const r=R();if(!r)return alert('Room is not ready.');const s=getState();s.page='room_match';r.fixtures=[];safeRender();try{r.fixtures=await fixtures();safeRender();}catch(e){console.error('Fixture load failed',e);safeRender();alert('Could not load matches. Press Refresh matches.');}};
  window.selectRoomFixture=async function(id){if(!leader())return;const r=R(),s=getState(),f=(r.fixtures||[]).find(x=>String(x.id)===String(id));if(!f)return alert('Match not found. Press Refresh matches.');const q=await supabase.from('match_rooms').update({selected_fixture_id:String(id),status:'locked'}).eq('id',r.room.id).eq('creator_id',s.user.id);if(q.error)return alert(q.error.message);r.fixture=f;r.players=[];try{r.players=await playersFor(f);}catch(e){console.warn('Player load failed',e);}s.page='room_team';safeRender();};
  window.openRoomTeam=async function(){const r=R(),s=getState();if(!r?.fixture)return alert('The room leader has not selected a match yet.');try{r.players=await playersFor(r.fixture);}catch(e){}s.page='room_team';safeRender();};
  window.roomPickPlayer=function(id){const r=R(),s=getState();if(!r||!s.user)return;const p=(r.players||[]).find(x=>String(x.id)===String(id));if(!p)return;const mine=r.picks||[];const already=mine.find(x=>String(x.user_id)===String(s.user.id)&&String(x.player_id)===String(id));if(already){r.picks=mine.filter(x=>!(String(x.user_id)===String(s.user.id)&&String(x.player_id)===String(id)));safeRender();return;}const pp=pos(p.position);if(!limits[pp])return alert('Only goalkeeper, defender, midfielder and striker players can be picked.');const own=mine.filter(x=>String(x.user_id)===String(s.user.id));if(count(own,pp)>=limits[pp])return alert('Position limit reached.');r.picks=mine.concat([{user_id:s.user.id,fixture_id:r.room.selected_fixture_id,player_id:p.id,slot_position:pp,players:p}]);safeRender();};
  window.saveRoomTeam=async function(){const r=R(),s=getState(),mine=(r.picks||[]).filter(x=>String(x.user_id)===String(s.user?.id));if(!Object.keys(limits).every(p=>count(mine,p)===limits[p]))return alert('Complete your 7-player team: 1 GK + 2 DEF + 3 MID + 1 ST.');const d=await supabase.from('room_player_picks').delete().eq('room_id',r.room.id).eq('user_id',s.user.id);if(d.error)return alert(d.error.message);const q=await supabase.from('room_player_picks').insert(mine.map(x=>({room_id:r.room.id,user_id:s.user.id,fixture_id:String(r.room.selected_fixture_id),player_id:x.player_id,slot_position:pos(x.slot_position)})));if(q.error)return alert(q.error.message);s.page='room_payment';safeRender();};
  function matchHtml(){const r=R(),fs=r?.fixtures||[],t=day(new Date()),tm=day(Date.now()+86400000);const section=(k,title)=>{const rows=fs.filter(f=>day(f.kickoff_at)===k);return '<section class="panel" style="margin-bottom:16px"><h3>'+title+'</h3>'+(rows.length?rows.map(f=>'<div class="row" style="margin-bottom:8px;gap:12px"><div style="flex:1"><b>'+esc(f.home_team)+' vs '+esc(f.away_team)+'</b><div class="small">'+ngTime(f.kickoff_at)+' Nigeria time</div></div><button class="primary" onclick="selectRoomFixture(\''+esc(f.id)+'\')">SELECT MATCH</button></div>').join(''):'<p class="muted">No fixture available.</p>')+'</section>';};return '<div class="wrap"><button class="back" onclick="backToRoom()">← Back to room</button><div class="section"><span class="badge">MATCH SELECTION</span><h2>Today & Tomorrow</h2></div>'+section(t,"TODAY'S MATCHES")+section(tm,"TOMORROW'S MATCHES")+'<button class="secondary" onclick="startRoomMatch()">↻ Refresh matches</button></div>';}
  function teamHtml(){const r=R(),s=getState(),mine=(r.picks||[]).filter(x=>String(x.user_id)===String(s.user?.id)),groups=[['GK','Goalkeepers'],['DEF','Defenders'],['MID','Midfielders'],['ST','Strikers']];let html='<div class="wrap"><button class="back" onclick="backToRoom()">← Back to room</button><h2>'+esc(r.fixture?.home_team)+' vs '+esc(r.fixture?.away_team)+'</h2><div class="notice">Pick exactly 7: 1 GK + 2 DEF + 3 MID + 1 ST. Selected: '+mine.length+'/7</div>';groups.forEach(g=>{const pp=g[0],label=g[1],list=(r.players||[]).filter(x=>pos(x.position)===pp);html+='<section class="panel" style="margin-bottom:14px"><h3>'+label+' '+count(mine,pp)+'/'+limits[pp]+'</h3>'+(list.length?list.map(p=>{const picked=mine.some(x=>String(x.player_id)===String(p.id));return '<button type="button" class="row" style="width:100%;margin-bottom:7px;text-align:left;cursor:pointer" onclick="roomPickPlayer(\''+esc(p.id)+'\')"><span><b>'+esc(p.name)+'</b><div class="small">'+esc(p.club||'')+'</div></span><span class="badge">'+(picked?'✓ UNPICK':'PICK')+'</span></button>';}).join(''):'<p class="muted">No players currently available in this position.</p>')+'</section>';});return html+'<button class="primary" onclick="saveRoomTeam()">Continue with 7 players →</button></div>';}
  function safeRender(){const s=getState(),app=document.querySelector('#app');if(!app)return;if(s.page==='room_match'){app.innerHTML=matchHtml();return;}if(s.page==='room_team'){app.innerHTML=teamHtml();return;}if(typeof window.render==='function'&&window.render!==safeRender){try{window.render();}catch(e){console.error('base render failed',e);}}}
  window.FOOTBALLPOINTS_ROOM_RULES={players:7,GK:1,DEF:2,MID:3,ST:1,entry:1000,feePercent:16,firstPercent:60,secondPercent:40,thirdDiamond:300};
  async function visibleFixtures(){const q=await supabase.from('upcoming_fixtures').select('id,home_team,away_team,kickoff_at,status').gte('kickoff_at',new Date(Date.now()-2*3600000).toISOString()).lte('kickoff_at',new Date(Date.now()+48*3600000).toISOString()).order('kickoff_at').limit(100);if(q.error){console.error('Visible match query failed',q.error);return [];}return q.data||[];}
  function immediateMatchesHtml(){const s=getState(),fs=s.fixtures||[],t=day(new Date()),tm=day(Date.now()+86400000);const section=(k,title)=>{const rows=fs.filter(f=>day(f.kickoff_at)===k);return '<section class="panel" style="margin-bottom:16px"><span class="badge">'+title+'</span>'+(rows.length?rows.map(f=>'<div class="fixture-card" style="display:flex;justify-content:space-between;align-items:center;gap:12px;margin:8px 0"><div><b>'+esc(f.home_team)+' vs '+esc(f.away_team)+'</b><div class="small">'+ngTime(f.kickoff_at)+' • Nigeria time</div></div><button class="primary" onclick="chooseImmediateMatch(\''+esc(f.id)+'\')">SELECT MATCH</button></div>').join(''):'<p class="muted">No match available for this day.</p>')+'</section>';};return '<div class="wrap"><span class="badge">STAKE A MATCH</span><h2>Choose a match</h2><p class="muted">Matches are shown immediately after login and are available to every staker.</p>'+section(t,"TODAY'S MATCHES")+section(tm,"TOMORROW'S MATCHES")+'<button class="secondary" onclick="showImmediateMatches()">↻ Refresh matches</button></div>';}
  window.showImmediateMatches=async function(){const s=getState();if(!s.user)return;s.page='matches';s.loadingFixtures=true;const app=document.querySelector('#app');if(app)app.innerHTML='<div class="wrap"><div class="panel"><h2>Loading matches…</h2><p class="muted">Fetching today and tomorrow fixtures.</p></div></div>';s.fixtures=await visibleFixtures();s.loadingFixtures=false;if(app)app.innerHTML=immediateMatchesHtml();};
  window.chooseImmediateMatch=async function(id){const s=getState(),f=(s.fixtures||[]).find(x=>String(x.id)===String(id));if(!f)return alert('Match not found. Refresh matches.');s.selectedFixtures=[f];s.page='builder';if(typeof window.start==='function')await window.start('league');};
  function patchEntry(){if(window.__FP_ENTRY_PATCHED)return true;if(!window.state)return false;window.__FP_ENTRY_PATCHED=true;const originalSignIn=window.signIn;if(typeof originalSignIn==='function'){window.signIn=async function(){await originalSignIn();if(window.state?.user)await window.showImmediateMatches();};}if(window.state.user)setTimeout(()=>window.showImmediateMatches(),50);return true;}
  let tries=0;const timer=setInterval(()=>{if(patchEntry()||++tries>150)clearInterval(timer);},100);
})();