/* Social room flow: chat -> leader selects one real match -> team picks -> payment. */
(function(){
const R={room:null,members:[],messages:[],fixtures:[],fixture:null,players:[],picks:[],payment:null,rooms:[]}; window.roomFlow=R; let poll=null,baseRender;
const e=v=>String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const n=()=>R.room?.game_mode==="quick6"?{GK:1,DEF:2,MID:2,ST:1}:{GK:1,DEF:4,MID:4,ST:2}; const sz=()=>Object.values(n()).reduce((a,b)=>a+b,0); const lead=()=>state.user&&R.room?.creator_id===state.user.id; const stop=()=>{if(poll){clearInterval(poll);poll=null;}};
async function safe(query,fallback=[]){try{const r=await query;return r.error?(console.warn("Room data query failed:",r.error.message),fallback):r.data||fallback;}catch(err){console.warn("Room data query failed:",err);return fallback;}}
async function load(id){
 const r=await supabase.from("match_rooms").select("*").eq("id",id).single();
 if(r.error)throw r.error;
 R.room=r.data;
 const [members,messages,fixture,picks,payment]=await Promise.all([
   safe(supabase.from("room_members").select("user_id,is_ready,profiles(display_name)").eq("room_id",id).order("joined_at")),
   safe(supabase.from("room_messages").select("user_id,message,created_at,profiles(display_name)").eq("room_id",id).order("created_at",{ascending:false}).limit(100)),
   R.room.selected_fixture_id?safe(supabase.from("upcoming_fixtures").select("id,home_team,away_team,kickoff_at,status").eq("id",R.room.selected_fixture_id).maybeSingle(),null):Promise.resolve(null),
   safe(supabase.from("room_player_picks").select("user_id,fixture_id,player_id,slot_position,players(id,name,club,position)").eq("room_id",id)),
   state.user?safe(supabase.from("room_payment_requests").select("id,amount,reference,status").eq("room_id",id).eq("user_id",state.user.id).order("created_at",{ascending:false}).limit(1),[]):Promise.resolve([])
 ]);
 R.members=members||[];R.messages=(messages||[]).reverse();R.fixture=fixture||null;R.picks=picks||[];R.payment=Array.isArray(payment)?payment[0]||null:payment||null;
}
async function refresh(){if(!R.room)return;const old=R.room.selected_fixture_id;try{await load(R.room.id);if(old!==R.room.selected_fixture_id)render();else if(state.page==='room')render();}catch(e){console.warn("Room refresh failed",e);}}
function startPoll(){stop();poll=setInterval(()=>{if(!R.room||!['room','room_match','room_team','room_payment'].includes(state.page))return stop();refresh();},3500);}
window.prepareRoomsPage=async()=>{const q=await supabase.from("match_rooms").select("*").eq("status","lobby").order("created_at",{ascending:false});R.rooms=q.data||[];window.roomState=R;};
window.makeRoomCode=()=>{const c="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";return "FP-"+Array.from({length:6},()=>c[Math.floor(Math.random()*c.length)]).join("");};
window.createRoom=async()=>{if(!state.user)return go("auth");const q=await supabase.from("match_rooms").insert({code:makeRoomCode(),name:document.querySelector("#roomName")?.value.trim()||"Stakers Room",visibility:document.querySelector("#roomVisibility")?.value||"private",game_mode:document.querySelector("#roomMode")?.value||"quick6",max_players:Math.max(2,Math.min(1000,+document.querySelector("#roomMax")?.value||10)),entry_fee:Math.max(0,Number(document.querySelector("#roomEntryFee")?.value||0)),creator_id:state.user.id,status:"lobby"}).select().single();if(q.error)return alert(q.error.message);const j=await supabase.from("room_members").insert({room_id:q.data.id,user_id:state.user.id});if(j.error)return alert(j.error.message);openRoom(q.data.id);};
window.joinRoomByCode=async()=>{if(!state.user)return go("auth");const code=document.querySelector("#joinCode")?.value.trim().toUpperCase();if(!code)return alert("Enter the room short code.");const q=await supabase.from("match_rooms").select("*").eq("code",code).eq("status","lobby").maybeSingle();if(q.error||!q.data)return alert("Room not found or closed.");const c=await supabase.from("room_members").select("user_id",{count:"exact",head:true}).eq("room_id",q.data.id);if(c.error)return alert(c.error.message);if((c.count||0)>=q.data.max_players)return alert("This room is full.");const j=await supabase.from("room_members").insert({room_id:q.data.id,user_id:state.user.id});if(j.error&&!j.error.message.toLowerCase().includes("duplicate"))return alert(j.error.message);await openRoom(q.data.id);};
window.joinRoomByCodePrefill=async code=>{const i=document.querySelector("#joinCode");if(i)i.value=code;await joinRoomByCode();};
window.openRoom=async id=>{stop();state.page="room";state.menuOpen=false;render();try{await load(id);render();startPoll();}catch(x){console.error("Could not load room",x);startPoll();alert("You joined the room, but some room data is still loading. The chat will retry automatically.");}};
window.toggleReady=async()=>{const m=R.members.find(x=>x.user_id===state.user.id);const q=await supabase.from("room_members").update({is_ready:!m?.is_ready}).eq("room_id",R.room.id).eq("user_id",state.user.id);if(q.error)return alert(q.error.message);await load(R.room.id);render();};
window.sendRoomMessage=async()=>{const i=document.querySelector("#roomChatInput"),msg=i?.value.trim();if(!msg)return;const q=await supabase.from("room_messages").insert({room_id:R.room.id,user_id:state.user.id,message:msg});if(q.error)return alert(q.error.message);i.value="";await load(R.room.id);render();};
window.startRoomMatch=async()=>{if(!lead())return alert("Only the room leader can choose the match.");state.page="room_match";render();await syncFixtures();const q=await supabase.from("upcoming_fixtures").select("id,home_team,away_team,kickoff_at,status").eq("status","scheduled").order("kickoff_at").limit(50);R.fixtures=q.data||[];render();};
window.selectRoomFixture=async id=>{if(!lead())return;const q=await supabase.from("match_rooms").update({selected_fixture_id:String(id),status:"locked"}).eq("id",R.room.id).eq("creator_id",state.user.id);if(q.error)return alert(q.error.message);await load(R.room.id);await loadPlayers();state.page="room_team";render();};
async function loadPlayers(){if(!R.fixture)return;const q=await supabase.from("players").select("id,name,club,position").eq("active",true).order("name");R.players=(q.data||[]).filter(p=>[R.fixture.home_team,R.fixture.away_team].includes(p.club));}
window.openRoomTeam=async()=>{if(!R.fixture)return alert("The room leader has not selected a match yet.");await loadPlayers();state.page="room_team";render();};
window.roomPickPlayer=id=>{const p=R.players.find(x=>x.id===id),mine=R.picks.filter(x=>x.user_id===state.user.id);if(!p||mine.some(x=>x.player_id===id))return;if(mine.filter(x=>x.slot_position===p.position).length>=n()[p.position])return alert(`You can pick only ${n()[p.position]} ${p.position} player(s).`);R.picks.push({user_id:state.user.id,fixture_id:R.room.selected_fixture_id,player_id:id,slot_position:p.position,players:p});render();};
window.roomRemovePlayer=id=>{R.picks=R.picks.filter(x=>!(x.user_id===state.user.id&&x.player_id===id));render();};
window.saveRoomTeam=async()=>{const mine=R.picks.filter(x=>x.user_id===state.user.id);if(!Object.keys(n()).every(k=>mine.filter(x=>x.slot_position===k).length===n()[k]))return alert(`Complete all ${sz()} positions before continuing.`);await supabase.from("room_player_picks").delete().eq("room_id",R.room.id).eq("user_id",state.user.id);const q=await supabase.from("room_player_picks").insert(mine.map(x=>({room_id:R.room.id,user_id:state.user.id,fixture_id:String(R.room.selected_fixture_id),player_id:x.player_id,slot_position:x.slot_position})));if(q.error)return alert(q.error.message);await load(R.room.id);state.page="room_payment";render();};
window.submitRoomPayment=async()=>{const fee=Number(R.room.entry_fee||0);if(fee<=0)return backToRoom();const ref=document.querySelector("#roomPaymentReference")?.value.trim();if(!ref)return alert("Enter your transfer reference/narration.");const q=await supabase.from("room_payment_requests").insert({room_id:R.room.id,user_id:state.user.id,amount:fee,method:"Bank transfer",reference:ref,status:"pending"});if(q.error)return alert(q.error.message);await load(R.room.id);backToRoom();};
window.backToRoom=()=>{state.page="room";render();};
window.roomsPage=()=>`<div class="section"><div><span class="badge">STAKERS LOUNGE</span><h2>Create or find a room</h2><p class="muted">Rooms are for chatting, meeting other stakers and planning together. Matches are chosen only after the room leader starts setup.</p></div></div><div class="room-actions"><div class="panel"><h3>Create your room</h3><input id="roomName" placeholder="Room name" value="My Stakers Room"><select id="roomVisibility"><option value="private">Private — code required</option><option value="public">Public — lobby</option></select><select id="roomMode"><option value="quick6">Quick 6 — 1 GK, 2 DEF, 2 MID, 1 ST</option><option value="classic11">Classic 11 — 1 GK, 4 DEF, 4 MID, 2 ST</option></select><input id="roomMax" type="number" min="2" max="1000" value="10"><input id="roomEntryFee" type="number" min="0" step="0.01" value="0" placeholder="Entry fee (optional)"><div class="notice"><b>Room first.</b> No matches are listed here. Create the room, share the generated code, chat and meet your stakers, then the leader chooses the real match for everyone.</div><button class="primary" onclick="createRoom()">Create room & generate code</button></div><div class="panel"><h3>Join with code</h3><input id="joinCode" placeholder="FP-ABC123"><button class="primary" onclick="joinRoomByCode()">Join room</button><hr><h3>Open rooms</h3>${(R.rooms||[]).map(r=>`<div class="room-card"><div><b>${e(r.name)}</b><div class="small">${e(r.game_mode)} • ${r.max_players} max • ${Number(r.entry_fee||0)>0?'Entry '+Number(r.entry_fee).toFixed(2):'No entry fee'}</div></div><button class="secondary" onclick="joinRoomByCodePrefill('${e(r.code)}')">Join</button></div>`).join('')||'<p class="muted">No public rooms waiting.</p>'}</div></div>`;
function nav(content){const L=['home','rooms','rounds','friendly','leaderboard'];return `<header class="top"><div class="brand">Football<span>Points</span></div><nav class="nav">${L.map(p=>`<button class="${state.page===p?'active':''}" onclick="go('${p}')">${p[0].toUpperCase()+p.slice(1)}</button>`).join('')}${state.user?`<button onclick="go('wallet')">Wallet</button><button onclick="loadAdmin()">Admin</button>`:''}</nav><div class="top-right">${state.user?`<button class="secondary desktop-only" onclick="signOut()">Sign out</button>`:`<button class="secondary desktop-only" onclick="go('auth')">Login</button>`}</div></header><main class="wrap">${content}</main>`;}
function lobby(){return `<div class="section"><div><span class="badge">ROOM ${e(R.room.code)}</span><h2>${e(R.room.name)}</h2><p class="muted">Chat, meet stakers and agree on the match together.</p></div><button class="secondary" onclick="go('rooms')">← Rooms</button></div><div class="room-grid"><div class="panel"><h3>Room chat</h3><div class="room-chat">${R.messages.map(m=>`<div class="chat-line"><b>${e(m.profiles?.display_name||'Player')}</b><span>${e(m.message)}</span><small>${new Date(m.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</small></div>`).join('')||'<p class="muted">No messages yet. Say hello and plan your match.</p>'}</div><div class="room-chat-input"><input id="roomChatInput" maxlength="1000" placeholder="Message the room..." onkeydown="if(event.key===\'Enter\')sendRoomMessage()"><button class="primary" onclick="sendRoomMessage()">Send</button></div></div><div class="panel"><h3>Players ${R.members.length}/${R.room.max_players}</h3>${R.members.map(m=>`<div class="row"><span>${e(m.profiles?.display_name||'Player')}${m.user_id===R.room.creator_id?' 👑':''}</span><span>${m.is_ready?'🟢 Ready':'⚪ In room'}</span></div>`).join('')}<button class="secondary" onclick="toggleReady()">Ready / Not ready</button><div class="room-code"><small>Share this code</small><strong>${e(R.room.code)}</strong></div><div class="notice"><b>${Number(R.room.entry_fee||0)>0?'Entry fee: '+Number(R.room.entry_fee).toFixed(2):'No entry fee set'}</b><br>${R.fixture?`Match selected: ${e(R.fixture.home_team)} vs ${e(R.fixture.away_team)}`:'No match selected yet. The room stays in chat mode until the leader starts setup.'}</div>${lead()&&!R.room.selected_fixture_id?'<button class="primary" style="width:100%;margin-top:10px" onclick="startRoomMatch()">Leader: choose the match →</button>':''}${R.room.selected_fixture_id?'<button class="primary" style="width:100%;margin-top:10px" onclick="openRoomTeam()">Pick players for this match →</button>':''}</div></div>`;}
function match(){return `<button class="back" onclick="backToRoom()">← Back to room</button><div class="section"><h2>Choose the match for everyone</h2></div><div class="grid">${R.fixtures.map(f=>`<div class="card"><span class="badge">${new Date(f.kickoff_at).toLocaleString()}</span><h3>${e(f.home_team)} vs ${e(f.away_team)}</h3><button class="primary" onclick="selectRoomFixture('${e(f.id)}')">Use this match</button></div>`).join('')||'<div class="card"><p class="muted">No scheduled matches are available.</p></div>'}</div>`;}
function team(){const mine=R.picks.filter(x=>x.user_id===state.user.id),N=n(),slots=['GK',...Array(N.DEF).fill('DEF'),...Array(N.MID).fill('MID'),...Array(N.ST).fill('ST')];return `<button class="back" onclick="backToRoom()">← Back to room</button><div class="section"><div><span class="badge">TEAM SELECTION</span><h2>${e(R.fixture.home_team)} vs ${e(R.fixture.away_team)}</h2><p class="muted">Everyone picks ${sz()} players for the same match.</p></div><span class="badge">${mine.length}/${sz()}</span></div><div class="builder"><div class="panel"><h3>Your team</h3><div class="formation">${slots.map(pos=>{const p=mine.find(x=>x.slot_position===pos)?.players;return `<div class="slot ${pos==='GK'?'gk':''} ${p?'filled':''}">${p?`<div><b>${e(p.name)}</b><div class="small">${e(p.club||'')}</div><button class="small" onclick="roomRemovePlayer('${e(p.id)}')">Remove</button></div>`:pos}</div>`}).join('')}</div><button class="primary" style="width:100%;margin-top:12px" onclick="saveRoomTeam()">Continue to payment →</button></div><div class="panel"><h3>Players</h3>${['GK','DEF','MID','ST'].map(pos=>`<h4>${pos}</h4>${R.players.filter(p=>p.position===pos).map(p=>`<div class="row"><div><b>${e(p.name)}</b><div class="small">${e(p.club||'')} • ${e(p.position)}</div></div><button class="secondary" onclick="roomPickPlayer('${e(p.id)}')">${mine.some(x=>x.player_id===p.id)?'Selected':'Pick'}</button></div>`).join('')||`<p class="muted">No ${pos} players found.</p>`}`).join('')}</div></div>`;}
function payment(){const fee=Number(R.room.entry_fee||0);return `<button class="back" onclick="backToRoom()">← Back to room</button><div class="section"><h2>Payment</h2><p class="muted">Your team is saved for ${e(R.fixture?.home_team||'')} vs ${e(R.fixture?.away_team||'')}.</p></div><div class="panel">${fee<=0?'<div class="notice"><b>No payment is required.</b></div><button class="primary" onclick="backToRoom()">Finish → Room</button>':R.payment?.status==='pending'?'<div class="notice">🟡 Payment submitted and waiting for verification.</div><button class="primary" onclick="backToRoom()">Return to room</button>':`<h3>Entry fee: ${fee.toFixed(2)}</h3><p class="muted">Payment is handled by bank transfer. Use the payment details available in your Wallet, then submit your transfer reference.</p><input id="roomPaymentReference" placeholder="Transfer reference / narration"><button class="primary" style="margin-top:10px" onclick="submitRoomPayment()">I have made the payment</button>`}</div>`;}
function install(){if(baseRender||typeof window.render!=='function'||!window.state)return setTimeout(install,100);baseRender=window.render;window.render=async()=>{if(state.page==='rooms'){await prepareRoomsPage();return baseRender();}if(R.room&&['room','room_match','room_team','room_payment'].includes(state.page)){document.querySelector('#app').innerHTML=nav(state.page==='room'?lobby():state.page==='room_match'?match():state.page==='room_team'?team():payment());return;}return baseRender();};}
install();
})();