/* FootballPoints FINAL 7-player picker.
   Required: 1 GK + 2 DEF + 3 MID + 1 ST = 7 players.
   Players are grouped by position, deduplicated, and loaded from both roster tables.
*/
(function(){
  const FORM={GK:1,DEF:2,MID:3,ST:1};
  const TOTAL=7;
  const esc=v=>String(v??'').replace(/[&<>\"]/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[s]||s));
  const pos=v=>{const p=String(v||'').toUpperCase().trim();if(['GK','G','GKP','GOALKEEPER','KEEPER'].includes(p))return 'GK';if(['DEF','DF','D','DEFENDER','BACK'].includes(p))return 'DEF';if(['MID','MF','M','MIDFIELDER','CM','DM','AM'].includes(p))return 'MID';if(['ST','FW','F','CF','FORWARD','STRIKER','ATTACKER'].includes(p))return 'ST';return p;};
  const norm=v=>String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');
  const sameClub=(a,b)=>{const x=norm(a),y=norm(b);return x&&y&&(x===y||x.includes(y)||y.includes(x));};
  const picked=id=>(state.selected||[]).some(p=>String(p.id)===String(id));
  const count=p=>(state.selected||[]).filter(x=>pos(x.position)===p).length;
  function dedupe(list){const seen=new Set();const out=[];for(const p of list||[]){const pp=pos(p.position);if(!FORM[pp])continue;const key=`${String(p.name||'').trim().toLowerCase()}|${norm(p.club)}|${pp}`;if(seen.has(key))continue;seen.add(key);out.push({...p,position:pp});}return out;}
  async function roster(f){
    const clubs=[f.home_team,f.away_team].filter(Boolean);let rows=[];
    const q=await supabase.from('players').select('id,name,club,position,photo_url,team_provider_id').eq('active',true).order('name');
    if(!q.error)rows=(q.data||[]).filter(p=>clubs.some(c=>sameClub(p.club,c)));
    const teamsQ=await supabase.from('fp_teams').select('id,name,provider_team_id,logo_url');
    const teams=(teamsQ.data||[]).filter(t=>clubs.some(c=>sameClub(t.name,c)));
    if(teams.length){
      const ids=teams.map(t=>t.id);const map=new Map(teams.map(t=>[String(t.id),t.name]));
      const pQ=await supabase.from('fp_players').select('id,name,position,photo_url,team_id,number').eq('active',true).in('team_id',ids).order('name');
      if(!pQ.error)for(const p of (pQ.data||[]))rows.push({...p,club:map.get(String(p.team_id))||''});
    }
    return dedupe(rows).sort((a,b)=>pos(a.position).localeCompare(pos(b.position))||String(a.club).localeCompare(String(b.club))||String(a.name).localeCompare(String(b.name)));
  }
  async function syncInBackground(f){try{const fx=await supabase.from('upcoming_fixtures').select('league_name,external_id').eq('id',f.id).maybeSingle();const league=fx.data?.league_name||'';if(league)await supabase.functions.invoke('pablo-roster-sync',{body:{league,home_team:f.home_team,away_team:f.away_team}});}catch(e){console.warn('Background roster sync:',e.message);}}
  function playerButton(p){const pp=pos(p.position),is=picked(p.id),full=!is&&count(pp)>=FORM[pp];return `<button type="button" class="row" style="width:100%;display:flex;align-items:center;text-align:left;cursor:${full?'not-allowed':'pointer'};opacity:${full&&!is?'.45':'1'};background:${is?'rgba(80,214,143,.12)':'transparent'};border:1px solid ${is?'rgba(80,214,143,.55)':'rgba(120,150,190,.25)'};margin-bottom:8px" onclick="toggleMatchPlayer('${esc(p.id)}')" ${full&&!is?'disabled':''}>${p.photo_url?`<img src="${esc(p.photo_url)}" alt="" style="width:38px;height:38px;border-radius:50%;object-fit:cover;margin-right:10px">`:`<span style="display:inline-flex;width:38px;height:38px;border-radius:50%;align-items:center;justify-content:center;background:#16304b;margin-right:10px">⚽</span>`}<div style="flex:1"><b>${esc(p.name)}</b><div class="small">${esc(p.club||'Team')}${p.number?` · #${esc(p.number)}`:''}</div></div><span class="badge">${is?'✓ UNPICK':full?'FULL':'PICK'}</span></button>`;}
  function normalSelected(){return state.selected||[];}
  window.toggleMatchPlayer=function(id){const p=(state.matchPlayers||[]).find(x=>String(x.id)===String(id));if(!p)return;const pp=pos(p.position);if(picked(id)){state.selected=normalSelected().filter(x=>String(x.id)!==String(id));return render();}if(!FORM[pp])return alert('This player position is not allowed.');if(count(pp)>=FORM[pp])return alert(`You can pick only ${FORM[pp]} ${pp} player(s).`);state.selected=[...normalSelected(),{...p,position:pp}];render();};
  window.submitMatchTeam=async function(){const s=normalSelected();if(!Object.keys(FORM).every(k=>s.filter(p=>pos(p.position)===k).length===FORM[k]))return alert('Complete your 7-player team: 1 goalkeeper, 2 defenders, 3 midfielders and 1 striker.');if(typeof window.submitTeam==='function')return window.submitTeam();};
  window.submitTeam=async function(){
    if(!state.user)return go('auth');const s=normalSelected();if(!Object.keys(FORM).every(k=>s.filter(p=>pos(p.position)===k).length===FORM[k]))return alert('Complete your 7-player team: 1 goalkeeper, 2 defenders, 3 midfielders and 1 striker.');
    const fixtureIds=(state.selectedFixtures||[]).map(f=>f.id).filter(Boolean);
    if(state.mode==='friendly'&&state.friendlyMatchId){
      const {data:entry,error:e1}=await supabase.from('friendly_match_entries').insert({match_id:state.friendlyMatchId,user_id:state.user.id,submitted_at:new Date().toISOString()}).select().single();if(e1)return alert(e1.message);
      const {error:e2}=await supabase.from('friendly_match_entry_players').insert(s.map(p=>({entry_id:entry.id,player_id:p.id,slot_position:pos(p.position)})));if(e2){await supabase.from('friendly_match_entries').delete().eq('id',entry.id);return alert(e2.message);}state.page='friendly';render();return;
    }
    const {data:round,error:re}=await supabase.from('rounds').select('id').eq('status','open').order('created_at',{ascending:false}).limit(1).maybeSingle();if(re)return alert(re.message);if(!round?.id)return alert('No OPEN round exists in Supabase.');
    const {data:entry,error:e1}=await supabase.from('entries').insert({round_id:round.id,user_id:state.user.id,submitted_at:new Date().toISOString()}).select().single();if(e1)return alert(e1.message);
    const {error:e2}=await supabase.from('entry_players').insert(s.map(p=>({entry_id:entry.id,player_id:p.id,slot_position:pos(p.position)})));if(e2){await supabase.from('entries').delete().eq('id',entry.id);return alert(e2.message);}
    if(fixtureIds.length)await supabase.from('entry_fixtures').upsert(fixtureIds.map(fixture_id=>({entry_id:entry.id,fixture_id})),{onConflict:'entry_id,fixture_id'});
    alert('7-player team saved.');state.page='leaderboard';render();
  };
  window.matchDetailPage=async function(){
    const f=state.selectedFixtures?.[0];if(!f)return `<div class="panel"><p class="muted">No match selected.</p><button class="primary" onclick="go('matches')">Back to matches</button></div>`;
    const players=await roster(f);state.matchPlayers=players;
    const s=normalSelected();const complete=Object.keys(FORM).every(k=>s.filter(p=>pos(p.position)===k).length===FORM[k]);
    const titles={GK:'🧤 Goalkeepers',DEF:'🛡️ Defenders',MID:'⚙️ Midfielders',ST:'⚽ Strikers'};
    const sections=Object.keys(FORM).map(k=>{const rows=players.filter(p=>pos(p.position)===k);return `<div class="panel"><div style="display:flex;justify-content:space-between;align-items:center"><h3>${titles[k]}</h3><span class="badge">${count(k)}/${FORM[k]}</span></div>${rows.map(playerButton).join('')||`<div class="notice"><b>No ${titles[k].replace(/^\S+ /,'').toLowerCase()} found yet.</b><br><span class="muted">The roster sync is being refreshed. Please use Refresh roster below.</span></div>`}</div>`;}).join('');
    const missing=Object.keys(FORM).filter(k=>players.filter(p=>pos(p.position)===k).length<FORM[k]);
    const selectedHtml=s.length?`<div class="notice" style="margin-top:16px"><b>Your team: ${s.length}/${TOTAL}</b><div style="margin-top:8px">${s.map(p=>`<button type="button" class="badge" style="margin:3px;cursor:pointer" onclick="toggleMatchPlayer('${esc(p.id)}')">${esc(p.name)} · ${esc(pos(p.position))} ×</button>`).join('')}</div></div>`:'';
    setTimeout(async()=>{await syncInBackground(f);try{const fresh=await roster(f);if(fresh.length>players.length){state.matchPlayers=fresh;if(state.page==='matchDetail')render();}}catch(e){}},0);
    return `<button class="back" onclick="go('matches')">← Back to matches</button><div class="section"><div><span class="badge">7-PLAYER MATCH</span><h2>${esc(f.home_team)} vs ${esc(f.away_team)}</h2><p class="muted">🕒 ${f.kickoff_at?new Date(f.kickoff_at).toLocaleString('en-NG',{timeZone:'Africa/Lagos',dateStyle:'medium',timeStyle:'short'}):'Kickoff TBD'} (Nigeria time)</p></div><button class="primary" onclick="submitMatchTeam()" ${complete?'':'disabled'}>${complete?'Save 7 players →':`Pick ${TOTAL-s.length} more`}</button></div>${selectedHtml}<div class="notice"><b>Required: 1 GK + 2 DEF + 3 MID + 1 ST = 7 players.</b><br><span class="muted">Players are grouped by position. Duplicate roster records are removed. You will never be asked to pick a goalkeeper-only or incomplete position list.</span></div>${missing.length?`<div class="notice" style="border-color:#d9a441"><b>Roster still updating:</b> missing ${missing.map(k=>titles[k]).join(', ')}. The match remains visible while the roster refreshes.</div>`:''}<div class="two" style="margin-top:16px">${sections}</div>`;
  };
  window.roomPickPlayer=function(id){const R=window.roomFlow,p=(R?.players||[]).find(x=>String(x.id)===String(id));if(!p)return;const pp=pos(p.position),mine=(R.picks||[]).filter(x=>x.user_id===state.user.id);if(mine.some(x=>String(x.player_id)===String(id))){R.picks=R.picks.filter(x=>!(x.user_id===state.user.id&&String(x.player_id)===String(id)));return render();}if(!FORM[pp])return alert('Only GK, DEF, MID and ST are allowed.');if(mine.filter(x=>pos(x.slot_position||x.players?.position)===pp).length>=FORM[pp])return alert(`You can pick only ${FORM[pp]} ${pp} player(s).`);R.picks.push({user_id:state.user.id,fixture_id:R.room.selected_fixture_id,player_id:id,slot_position:pp,players:p});render();};
  window.saveRoomTeam=async function(){const R=window.roomFlow,mine=(R?.picks||[]).filter(x=>x.user_id===state.user.id);if(!Object.keys(FORM).every(k=>mine.filter(x=>pos(x.slot_position||x.players?.position)===k).length===FORM[k]))return alert('Complete your 7-player team: 1 goalkeeper, 2 defenders, 3 midfielders and 1 striker.');const del=await supabase.from('room_player_picks').delete().eq('room_id',R.room.id).eq('user_id',state.user.id);if(del.error)return alert(del.error.message);const ins=await supabase.from('room_player_picks').insert(mine.map(x=>({room_id:R.room.id,user_id:state.user.id,fixture_id:String(R.room.selected_fixture_id),player_id:x.player_id,slot_position:pos(x.slot_position||x.players?.position)})));if(ins.error)return alert(ins.error.message);await R && window.openRoom(R.room.id);};
  function renderRoomTeam(){const R=window.roomFlow;if(!R?.fixture)return;const mine=(R.picks||[]).filter(x=>x.user_id===state.user.id);const players=dedupe(R.players||[]);const titles={GK:'🧤 Goalkeepers',DEF:'🛡️ Defenders',MID:'⚙️ Midfielders',ST:'⚽ Strikers'};const complete=Object.keys(FORM).every(k=>mine.filter(x=>pos(x.slot_position||x.players?.position)===k).length===FORM[k]);const selected=mine.map(x=>x.players).filter(Boolean);const cards=Object.keys(FORM).map(k=>`<div class="panel"><div style="display:flex;justify-content:space-between"><h3>${titles[k]}</h3><span class="badge">${mine.filter(x=>pos(x.slot_position||x.players?.position)===k).length}/${FORM[k]}</span></div>${players.filter(p=>pos(p.position)===k).map(p=>{const is=mine.some(x=>String(x.player_id)===String(p.id));const full=!is&&mine.filter(x=>pos(x.slot_position||x.players?.position)===k).length>=FORM[k];return `<button type="button" class="row" style="width:100%;display:flex;text-align:left;align-items:center;cursor:${full?'not-allowed':'pointer'};opacity:${full&&!is?'.45':'1'};background:${is?'rgba(80,214,143,.12)':'transparent'};margin-bottom:8px" onclick="roomPickPlayer('${esc(p.id)}')" ${full&&!is?'disabled':''}><div style="flex:1"><b>${esc(p.name)}</b><div class="small">${esc(p.club||'Team')}</div></div><span class="badge">${is?'✓ UNPICK':full?'FULL':'PICK'}</span></button>`;}).join('')||'<p class="muted">No players in this position yet. Roster refresh is running.</p>'}</div>`).join('');document.querySelector('main.wrap').innerHTML=`<button class="back" onclick="backToRoom()">← Back to room</button><div class="section"><div><span class="badge">7-PLAYER TEAM</span><h2>${esc(R.fixture.home_team)} vs ${esc(R.fixture.away_team)}</h2><p class="muted">Pick exactly 1 GK + 2 DEF + 3 MID + 1 ST.</p></div><button class="primary" onclick="saveRoomTeam()" ${complete?'':'disabled'}>${complete?'Save 7-player team →':`Pick ${TOTAL-mine.length} more`}</button></div><div class="notice"><b>Your team: ${mine.length}/${TOTAL}</b>${selected.length?`<div style="margin-top:8px">${selected.map(p=>`<span class="badge" style="margin:3px">${esc(p.name)} · ${esc(pos(p.position))}</span>`).join('')}</div>`:''}</div><div class="two" style="margin-top:16px">${cards}</div>`;}
  const baseRender=window.render;window.render=async function(){await baseRender();if(state.page==='room_team')renderRoomTeam();};
})();
