(function(){
  const STYLE=`#fpSupportFab{position:fixed;right:16px;bottom:16px;z-index:10000;border:0;border-radius:999px;padding:12px 16px;background:#55d98b;color:#04130b;font-weight:900;box-shadow:0 8px 30px #0006;cursor:pointer}#fpSupportModal{position:fixed;inset:0;z-index:10001;background:#0008;display:none;align-items:flex-end;justify-content:center;padding:16px}#fpSupportCard{width:min(680px,100%);max-height:85vh;overflow:auto;background:#0d1b2e;color:#edf5ff;border:1px solid #28415e;border-radius:18px;padding:20px;box-shadow:0 20px 70px #0008}#fpSupportCard input,#fpSupportCard textarea{width:100%;box-sizing:border-box;margin:6px 0 10px;padding:11px;border-radius:9px;border:1px solid #29445f;background:#091626;color:#fff}.fpChat{max-height:280px;overflow:auto;padding:8px;background:#091626;border-radius:10px}.fpMsg{padding:9px 11px;margin:7px 0;border-radius:10px;background:#132c45}.fpMsg.me{background:#173b2c}.fpRow{display:flex;gap:8px;flex-wrap:wrap}.fpBtn{border:0;border-radius:8px;padding:10px 13px;font-weight:800;cursor:pointer}.fpPrimary{background:#55d98b;color:#04130b}.fpSecondary{background:#142941;color:#fff}.fpClose{float:right;background:transparent;color:#fff;border:0;font-size:22px;cursor:pointer}`;
  function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function ui(){if(document.getElementById('fpSupportFab'))return;const s=document.createElement('style');s.textContent=STYLE;document.head.appendChild(s);const b=document.createElement('button');b.id='fpSupportFab';b.textContent='💬 Customer Care';b.onclick=()=>{document.getElementById('fpSupportModal').style.display='flex';load()};document.body.appendChild(b);const m=document.createElement('div');m.id='fpSupportModal';m.innerHTML='<div id="fpSupportCard"><button class="fpClose" onclick="document.getElementById(\'fpSupportModal\').style.display=\'none\'">×</button><h2>Customer Care & Rewards</h2><div id="fpSupportBody">Loading...</div></div>';document.body.appendChild(m)}
  async function user(){const {data}=await supabase.auth.getUser();return data?.user||null}
  async function load(){const body=document.getElementById('fpSupportBody'),u=await user();if(!u){body.innerHTML='<p>Please sign in to contact Customer Care or use referrals.</p><button class="fpBtn fpPrimary" onclick="document.getElementById(\'fpSupportModal\').style.display=\'none\';go(\'auth\')">Sign in / Create account</button>';return}const [{data:threads,error:te},{data:ref,error:re}]=await Promise.all([supabase.from('support_threads').select('id,subject,status,created_at').eq('user_id',u.id).order('created_at',{ascending:false}),supabase.from('referral_codes').select('code,diamond_reward,total_referrals,total_earned').eq('user_id',u.id).maybeSingle()]);const code=ref?.code||'';const link=location.origin+location.pathname+'?ref='+encodeURIComponent(code);body.innerHTML=`<div><h3>💬 Talk to Admin</h3><input id="fpSubject" placeholder="Subject"><textarea id="fpMessage" rows="4" placeholder="Type your message..."></textarea><button class="fpBtn fpPrimary" onclick="fpTicket()">Send to Customer Care</button><h4>Your conversations</h4>${(threads||[]).map(t=>`<div class="fpMsg"><b>${esc(t.subject)}</b><br><small>${esc(t.status)} • ${new Date(t.created_at).toLocaleString()}</small><br><button class="fpBtn fpSecondary" onclick="fpThread('${t.id}')">Open</button></div>`).join('')||'<p>No conversations yet.</p>'}</div><hr><div><h3>💎 Refer Friends & Earn Diamonds</h3><p>Share this personal link. Each validated new referral earns <b>${Number(ref?.diamond_reward||100)} 💎</b>.</p><input readonly value="${esc(link)}"><div class="fpRow"><button class="fpBtn fpPrimary" onclick="navigator.clipboard?.writeText(this.parentElement.previousElementSibling.value);alert('Referral link copied')">Copy link</button><button class="fpBtn fpSecondary" onclick="navigator.share?.({title:'Football Points',text:'Join me on Football Points',url:'${esc(link)}'})">Share</button></div><p>Referrals: <b>${Number(ref?.total_referrals||0)}</b> • Diamonds earned: <b>${Number(ref?.total_earned||0)}</b></p></div>${(te||re)?'<p class="fpMsg">Customer Care/referral tables are not installed yet. Run supabase_upgrade.sql first.</p>':''}`}
  window.fpTicket=async()=>{const u=await user(),subject=document.getElementById('fpSubject').value.trim()||'Customer support',message=document.getElementById('fpMessage').value.trim();if(!message)return alert('Write a message first.');const {data:t,error}=await supabase.from('support_threads').insert({user_id:u.id,subject,status:'open'}).select().single();if(error)return alert(error.message);const {error:e}=await supabase.from('support_messages').insert({thread_id:t.id,sender_id:u.id,message});if(e)return alert(e.message);load()};
  window.fpThread=async(id)=>{const u=await user(),{data:t}=await supabase.from('support_threads').select('id,subject,status').eq('id',id).eq('user_id',u.id).single(),{data:msgs}=await supabase.from('support_messages').select('sender_id,message,created_at').eq('thread_id',id).order('created_at');document.getElementById('fpSupportBody').innerHTML=`<button class="fpBtn fpSecondary" onclick="load()">← Back</button><h3>${esc(t?.subject||'Conversation')}</h3><div class="fpChat">${(msgs||[]).map(m=>`<div class="fpMsg ${m.sender_id===u.id?'me':''}">${esc(m.message)}<br><small>${new Date(m.created_at).toLocaleString()}</small></div>`).join('')}</div><textarea id="fpReply" rows="3" placeholder="Reply..."></textarea><button class="fpBtn fpPrimary" onclick="fpReply('${id}')">Send reply</button>`};
  window.fpReply=async(id)=>{const u=await user(),message=document.getElementById('fpReply').value.trim();if(!message)return;const {error}=await supabase.from('support_messages').insert({thread_id:id,sender_id:u.id,message});if(error)return alert(error.message);fpThread(id)};
  const ref=new URLSearchParams(location.search).get('ref');if(ref)localStorage.setItem('fp_referral_code',ref.toUpperCase());
  window.addEventListener('load',()=>setTimeout(ui,300));
})();
