(function(){
  const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=x=>Number(x||0).toFixed(2);
  function modal(id,html){let m=document.getElementById(id);if(!m){m=document.createElement('div');m.id=id;m.style='position:fixed;inset:0;z-index:10050;background:#0009;display:flex;align-items:flex-end;justify-content:center;padding:16px';document.body.appendChild(m)}m.innerHTML='<div style="width:min(820px,100%);max-height:90vh;overflow:auto;background:#0d1b2e;color:#edf5ff;border:1px solid #28415e;border-radius:18px;padding:20px">'+html+'</div>';return m}
  async function wallet(){
    if(!state.user)return go('auth');
    const {data:w,error:we}=await supabase.from('game_wallets').select('cash_balance,points,diamonds,updated_at').eq('user_id',state.user.id).single();
    if(we)return alert(we.message);
    const {data:tx,error:te}=await supabase.from('wallet_ledger').select('tx_type,cash_delta,points_delta,diamonds_delta,description,created_at').eq('user_id',state.user.id).order('created_at',{ascending:false}).limit(50);
    if(te)return alert(te.message);
    const {data:wd}=await supabase.from('withdrawal_requests').select('amount,status,destination,created_at,processed_at').eq('user_id',state.user.id).order('created_at',{ascending:false}).limit(20);
    const {data:dp}=await supabase.from('deposit_requests').select('amount,method,reference,status,created_at,processed_at').eq('user_id',state.user.id).order('created_at',{ascending:false}).limit(20);
    const m=modal('fpWalletModal',`<button style="float:right;background:transparent;color:#fff;border:0;font-size:24px" onclick="this.closest('#fpWalletModal').remove()">×</button><span class="badge">WALLET</span><h2>My Wallet</h2><div class="grid"><div class="card"><b>Cash balance</b><h2>₦${money(w.cash_balance)}</h2></div><div class="card"><b>Points</b><h2>${Number(w.points||0)}</h2></div><div class="card"><b>Diamonds</b><h2>${Number(w.diamonds||0)}</h2></div></div><div class="two" style="margin-top:16px"><div class="panel"><h3>Deposit</h3><p class="muted">Send payment using your approved payment method, then submit the reference here. An admin reviews and credits the wallet.</p><input id="depAmount" type="number" min="1" step="0.01" placeholder="Amount (₦)"><input id="depMethod" placeholder="Method (e.g. bank transfer)"><input id="depRef" placeholder="Payment reference / proof note"><button class="primary" onclick="submitDeposit()">Submit deposit</button></div><div class="panel"><h3>Withdraw</h3><p class="muted">Withdrawal requests are reviewed and paid manually by an admin. Use a bank/account destination you control.</p><input id="wdAmount" type="number" min="1" step="0.01" placeholder="Amount (₦)"><input id="wdDest" placeholder="Bank name + account number + account name"><button class="primary" onclick="submitWithdrawal()">Request withdrawal</button></div></div><div class="panel" style="margin-top:16px"><h3>Recent transactions</h3>${(tx||[]).map(x=>`<div class="row"><span>${esc(x.description||x.tx_type)}<small class="muted"><br>${new Date(x.created_at).toLocaleString()}</small></span><b>₦${money(x.cash_delta)}</b></div>`).join('')||'<p class="muted">No transactions yet.</p>'}</div><div class="panel" style="margin-top:16px"><h3>Deposit requests</h3>${(dp||[]).map(x=>`<div class="row"><span>₦${money(x.amount)} • ${esc(x.method)}<small class="muted"><br>${esc(x.reference||'No reference')} • ${esc(x.status)}</small></span><small>${new Date(x.created_at).toLocaleString()}</small></div>`).join('')||'<p class="muted">No deposit requests.</p>'}</div><div class="panel" style="margin-top:16px"><h3>Withdrawal requests</h3>${(wd||[]).map(x=>`<div class="row"><span>₦${money(x.amount)} • ${esc(x.status)}<small class="muted"><br>${esc(x.destination)}</small></span><small>${new Date(x.created_at).toLocaleString()}</small></div>`).join('')||'<p class="muted">No withdrawal requests.</p>'}</div>`);m.style.display='flex';
  }
  window.submitDeposit=async function(){const amount=Number(document.getElementById('depAmount')?.value),method=document.getElementById('depMethod')?.value.trim(),ref=document.getElementById('depRef')?.value.trim();if(!amount||amount<=0||!method)return alert('Enter amount and payment method.');const q=await supabase.rpc('create_deposit_request',{p_amount:amount,p_method:method,p_reference:ref||null});if(q.error)return alert(q.error.message);alert('Deposit request submitted. An admin will review it.');wallet();};
  window.submitWithdrawal=async function(){const amount=Number(document.getElementById('wdAmount')?.value),dest=document.getElementById('wdDest')?.value.trim();if(!amount||amount<=0||!dest)return alert('Enter amount and withdrawal destination.');const q=await supabase.rpc('create_withdrawal_request',{p_amount:amount,p_destination:dest});if(q.error)return alert(q.error.message);alert('Withdrawal request submitted for admin review.');wallet();};
  window.openWallet=wallet;
  async function adminManagement(){const q=await supabase.rpc('admin_list_users');if(q.error)return alert(q.error.message);const users=q.data||[];modal('fpAdminUsersModal',`<button style="float:right;background:transparent;color:#fff;border:0;font-size:24px" onclick="this.closest('#fpAdminUsersModal').remove()">×</button><span class="badge">ADMIN</span><h2>Admin Management</h2><p class="muted">Only active users in the admin list can open the Admin dashboard. You remain the primary admin unless you deliberately add another.</p><div class="panel"><h3>Add another admin</h3><input id="newAdminEmail" type="email" placeholder="Registered user's email"><button class="primary" onclick="addAdminByEmail()">Grant admin access</button></div><div class="panel" style="margin-top:16px"><h3>Users</h3>${users.map(u=>`<div class="row"><span><b>${esc(u.display_name||u.email||u.user_id)}</b><small class="muted"><br>${esc(u.email||'')} • ${u.is_admin?'Admin':'User'}${u.is_admin?' • '+(u.active?'Active':'Disabled'):''}</small></span>${u.is_admin?`<button class="${u.active?'danger':'secondary'}" onclick="setAdmin('${u.user_id}',${!u.active})">${u.active?'Remove admin':'Restore admin'}</button>`:''}</div>`).join('')}</div>`);document.getElementById('fpAdminUsersModal').style.display='flex';}
  window.addAdminByEmail=async function(){const email=document.getElementById('newAdminEmail')?.value.trim();if(!email)return alert('Enter the registered user email.');const q=await supabase.rpc('add_admin_by_email',{p_email:email});if(q.error)return alert(q.error.message);alert('Admin access granted.');adminManagement();};
  window.setAdmin=async function(id,active){if(!confirm(active?'Restore this admin?':'Remove admin access from this user?'))return;const q=await supabase.rpc('set_admin_active',{p_user_id:id,p_active:active});if(q.error)return alert(q.error.message);adminManagement();};
  window.openAdminManagement=adminManagement;
  let tries=0;const hook=()=>{tries++;if(window.go&&!window.__walletHooked){const oldGo=window.go;window.go=function(p){if(p==='wallet'){state.page='wallet';state.menuOpen=false;return wallet();}return oldGo(p)};window.__walletHooked=true;}if(window.loadAdmin&&!window.__adminHooked){const oldAdmin=window.loadAdmin;window.loadAdmin=async function(){await oldAdmin();if(state.user){const ok=await supabase.rpc('is_admin');if(ok.data){const b=document.createElement('button');b.className='secondary';b.textContent='Manage Admins';b.style='margin:12px';b.onclick=adminManagement;document.querySelector('#app')?.appendChild(b);}}};window.__adminHooked=true;}if(tries<100&&( !window.__walletHooked || !window.__adminHooked))setTimeout(hook,100);} ;setTimeout(hook,0);
})();